### ISSUE TITLE
Theme Config

### ISSUE THREAD

**Issue by ryanfleury** [4coder-editor/4coder#101]
The default theme set in the config file is not loaded at startup in 4.1.0.

**Comment by BrieucSwales** [comment]
Here's a quick fix for this issue in the meantime. Put this at the end of the "default_startup" command or your custom startup command:

```
Color_Table_List *color_table_list = &global_theme_list;
for ( Color_Table_Node *node = color_table_list->first; node != 0; node = node->next ) {
    if ( string_match( node->name, global_config.default_theme_name ) ) {
        active_color_table = node->table;
        break;
    }
}
```

**Comment by 4coder-editor** [comment]
Fixed and incorporated into the config parser. Will be fixed in 4.1.1

**Comment by s0ra** [comment]
I added the code to the startup command (in the example?) and compiled but still couldn't change the theme.

**Comment by s0ra** [comment]
So, I finally got the theme working. The string need to match exactly without the suffix.
