### ISSUE TITLE
Macro recording / stopped visual highlight

### ISSUE THREAD

**Issue by Skytrias** [4coder-editor/4coder#102]
It would be nice if macro recording would be highlighted at the top bar or somewhere else to indicate it recording. 

This will prevent users from accidentally recording for long periods before realizing / maybe crashing the recorder. 

If you want to go crazy you could highlight the text in the editor thats being recorded.

**Comment by 4coder-editor** [comment]
Did this by adding an extended cursor color to the color themes.
