### ISSUE TITLE
"search_identifier" ctrl + t doesnt work on the start of a line anymore

### ISSUE THREAD

**Issue by Skytrias** [4coder-editor/4coder#107]
In alpha this used to be a thing that at you could still search with ctrl + t at the start of a line.
In beta this doesnt work anymore. 

It still works on the end of a word though.

**Comment by Skytrias** [comment]
short demonstration by mangchi_ 
https://cdn.discordapp.com/attachments/657067375681863703/657693539798614039/2019-12-20_22-18-05.mp4

**Comment by 4coder-editor** [comment]
Off by one in the enclosure function. Fixed in 4.1.1
