### ISSUE TITLE
move_down with consola.ttf font does nothing

### ISSUE THREAD

**Issue by GreyDodger** [4coder-editor/4coder#108]
4coder beta 4.1.0 super
Maybe not related but there seems to be a lot of empty space beneath the font
![image](https://user-images.githubusercontent.com/2457708/71136337-21a82700-21ca-11ea-9a0f-7263316e70d0.png)

**Comment by 4coder-editor** [comment]
Subtle issue with the new x,y coordinate system, addressed with a small tweak to the layout API in 4.1.1
