### ISSUE TITLE
The lister used for ‘interactive_switch_buffer’ has become case sensitive

### ISSUE THREAD

**Issue by embededhell** [4coder-editor/4coder#109]
In 4.1,
The lister calls  `string_find_first` with a ‘rule’ parameter of `StringMatch_CaseInsensitive.` (4code_base_types.cpp, line 4748 ish )
This function then tests for a single character match, which is case sensitive and fails if the case is different.
`if (str.str[i] == needle.str[0])`

**Comment by 4coder-editor** [comment]
Thanks for pointing out the source of the bug, it's fixed for 4.1.1
