### ISSUE TITLE
Implement a cursor stack for buffers

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#11]
To improve the cursor behavior when switching back to a buffer in multiple views at the same time, I think the cursor positions on each buffer should be stored as a stack.  When the user switches to a buffer, a cursor is popped off the stack for that buffer.  When the user switches away from a buffer, the cursor position is pushed onto the stack.

In addition to the stack, the "most recently moved cursor" should be stored in the buffer, and used whenever the cursor stack is empty.

\- Casey

**Comment by 4coder-editor** [comment]
I addressed this exactly as suggested.

**Comment by cmuratori** [comment]
This is very exciting!!  I have wanted this for a while...

\- Casey
