### ISSUE TITLE
Build Search (ALT-M) fails if there are spaces in the current directory

### ISSUE THREAD

**Issue by embededhell** [4coder-editor/4coder#110]
If there are spaces in the path parameter passed to `standard_build_exec_command`, the process fails as windows is truncating the command at the first space.

in 4coder_build_commands.cpp, `standard_search_and_build_from_dir`, modifying,
```
String_Const_u8 command = push_u8_stringf(scratch, "%.*s/%.*s",
                                                  string_expand(path),
                                                  string_expand(cmd_string));
```
to

```
String_Const_u8 command = push_u8_stringf(scratch, "\"%.*s/%.*s\"",
                                                  string_expand(path),
                                                  string_expand(cmd_string));
```

wrapping the commend in quotes fixes the issue at least for myself.

**Comment by 4coder-editor** [comment]
Applied the suggested fix, thanks. Fix in 4.1.1.
