### ISSUE TITLE
Fuzzy search in filebar is case sensitive in 4.1

### ISSUE THREAD

**Issue by Skytrias** [4coder-editor/4coder#111]
The filebar search is case sensitive and wont show the other case sensitive result.

pic from ryan
![grafik](https://user-images.githubusercontent.com/22886746/71285401-5b616500-2365-11ea-8f4a-a6e3f6179fae.png)
![grafik](https://user-images.githubusercontent.com/22886746/71285465-8b106d00-2365-11ea-9ed7-60305936649d.png)

**Comment by 4coder-editor** [comment]
Fixed in 4.1.1
