### ISSUE TITLE
execute_any_cli - Overwriting outbut buffer name

### ISSUE THREAD

**Issue by EverCursed** [4coder-editor/4coder#112]
**execute_any_cli**
When asked to enter a name for the output buffer, you can enter anything. 

![ss1](https://user-images.githubusercontent.com/25308743/71289220-9e5a1300-233a-11ea-8a13-d66ffc33c355.png)

After backspacing a bit... 

![ss2](https://user-images.githubusercontent.com/25308743/71289319-e0835480-233a-11ea-9f24-6571737b9581.png)

And entering something else...

![ss3](https://user-images.githubusercontent.com/25308743/71289330-ebd68000-233a-11ea-9315-9192e87598ed.png)

The resulting buffer name contains everything you deleted in the first place, overwritten by the new text entered. 

![ss4](https://user-images.githubusercontent.com/25308743/71289404-06a8f480-233b-11ea-9a6d-4e6e6e8366f5.png)

The old text entered also persists between different **execute_any_cli** calls.

**Comment by Leon280698** [comment]
Just to add: This does not only affect the output buffer name but also the command itself.

**Comment by 4coder-editor** [comment]
Dumb null terminated buffer bug - one of the few places in the code base that I haven't switched off of them yet - hacked around it for now so it's fixed in 4.1.1.
