### ISSUE TITLE
visual studio 2019 vcvars 

### ISSUE THREAD

**Issue by GabrielJadderson** [4coder-editor/4coder#115]
setup_cl_generic.bat should be updated to support visual studio 2019 like so: 
    
    SET VC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    IF NOT DEFINED LIB (IF EXIST "%VC_PATH%" (call "%VC_PATH%\VC\Auxiliary\Build\vcvarsall.bat" %1))

    SET VC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    IF NOT DEFINED LIB (IF EXIST "%VC_PATH%" (call "%VC_PATH%\VC\Auxiliary\Build\vcvarsall.bat" %1))

**Comment by 4coder-editor** [comment]
Added, thanks for the paths!
