### ISSUE TITLE
Quitting with unsaved changes doesn't work the first time

### ISSUE THREAD

**Issue by 2BJones** [4coder-editor/4coder#117]
Short video of the issue:
https://imgur.com/5EDlR2C

If you try to quit with unsaved changes, a menu comes up asking you to confirm.  If you select Yes, the menu disappears but the editor does not close.  Trying to quit again results in the editor closing immediately.  Making further changes after the first attempt does not bring back the confirmation menu either.

(Also, the menu reads, "There are one or more buffers with unsave changes, close anyway?", "unsave" should be "unsaved")

**Comment by 4coder-editor** [comment]
Problem in the exit menu handler logic. Fixed in 4.1.1.
