### ISSUE TITLE
KeyCode's missing

### ISSUE THREAD

**Issue by tebtro** [4coder-editor/4coder#122]
It seems like there are a few KeyCode's missing.
These would be for example Plus, Star, Tilda, Hashtag, ...

Some of these are on a seperate key on my keyboard (my keyboard layout is QWERTZ - German Austria), 
and so I can't bind to one of these keys.

**Comment by PascalBeyer** [comment]
I would like to add "alt gr" does not appear to set modifiers. If I press "alt-gr + 7" which is the german keyboard combination for '{' the output in *keyboard* is: 
k45 m{45 }
k46 m{46 }
k22 m{22 }
t7B
k22 ^m{22 }
k45 ^m{46 }
k46 ^
I.e. it presses Ctrl and Alt and 7 and writes '{'.

**Comment by ryanbyczek** [comment]
Just wanted to add, it looks like even on a US keyboard there is no way to map Num Pad keys like: / * - + . which is a real bummer for me.

**Comment by 4coder-editor** [comment]
I've extended the key code list with numpad codes and "extra" codes. The contributors and I still need to see to it that the mappings are applied on every OS.

I've also provided a new key stroke details viewer, which will allow you to hit a key and see the key code (name and value) that maps to that key.

**Comment by tebtro** [comment]
Awesome, the key details viewer is really helpful.
I am on Windows 10 and I am using the Dvorak Programmer keyboard layout right now.
And with the new 4coder version I am able to bind to every key.

Only haven't tried numpad, because my keyboard is a tenkeyless.

**Comment by PascalBeyer** [comment]
Alt-gr still does not seem to set modifiers. The keycodes now work for me.

**Comment by 4coder-editor** [comment]
@PascalBeyer If you are unaware you can enable `lalt_lctrl_is_altgr` to get Alt+Ctrl to do Alt-gr. I believe every last key code that windows can report is now bound to something, and with the `display_key_code` command it should be possible to track them down.

**Comment by 4coder-editor** [comment]
I believe every last key code that windows can report is now bound to something, and with the `display_key_code` command it should be possible to track them down.
