### ISSUE TITLE
[Feature Request] Suggestion for Make directory command

### ISSUE THREAD

**Issue by exanimusfan** [4coder-editor/4coder#123]
When you want to create a file, you can use the open file function and the write the name to a file that doesn't exist. It would be nice to have the same for directories like in emacs.

The way that works is you write a '/' after the name of the file, press return and than 4coder could ask you if you want to create a directory. Or if you write a file name after '/' and then save that file, 4coder should either create the file and the directory, or ask you if you want to create the directory.

**Comment by 4coder-editor** [comment]
I added the a feature to the file dialogue to ask if you want to create a folder whenever you insert a slash after a folder that doesn't already exist.  Good suggestion, thanks!  The feature is in 4.1.2.
