### ISSUE TITLE
Replacing highlighted characters with a bracket results in a crash

### ISSUE THREAD

**Issue by PolarJunction** [4coder-editor/4coder#124]
To reproduce:
1. Open a .cpp file.
2. Highlight the last 3+ letters of a line, replace with a ')' or '}'.
3. Observe crash.

It doesn't always have to be at the end of a line, but I've found it happens almost every time, even on comments.

**Comment by 4coder-editor** [comment]
I haven't been able to reproduce this crash. Can you confirm that it is happening in 4.1.1? If so I'll ask for more details about your configuration including your config.4coder file, any customizations you're using, and if you have a particular .cpp file you can share that definitely causes this and the location in the file, that might help too.

**Comment by 4coder-editor** [comment]
I believe I tracked this down after the extra info from https://github.com/4coder-editor/4coder/issues/224
