### ISSUE TITLE
Highlighting many lines results in severe "lag"

### ISSUE THREAD

**Issue by PolarJunction** [4coder-editor/4coder#126]
Highlighting a file with many (50+) lines results in a sudden CPU increase and 4coder slows down dramatically.

Using resource manager I saw the CPU usage jump from 0.4% to 15% when highlighting a file.

**Comment by EverCursed** [comment]
I think you can try recompiling the custom library with optimizations turned on. This solved a few performance problems for me.

**Comment by 4coder-editor** [comment]
There was a completely unnecessary extra loop in the routine that highlights ranges left over from an old version of the function. This should be a lot better in 4.1.2.
