### ISSUE TITLE
Cleaner token access

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#13]
It needs to be simpler to get and examine tokens.  If I understand correctly, once the lexer completes, then the token stream is built and it doesn't change inside an API callback.  If this is so, it would be much more efficient if the custom layer could get tokens back quickly and cleanly using a small, clear set of APIs that does not involve needing to do the "token caching" stuff that's happening in a lot of the custom layer right now.  It would be nice, too, if the tokens returned during iteration included not only the start/end position, but also a pointer to the contiguous token text, since presumably this is stable at that time and won't move until the next buffer edit?  This would involve lots of spurious buffer copying and wasted memory allocations for housing temporary token contents.

\- Casey

**Comment by 4coder-editor** [comment]
The iterator for tokens is now setup.  Still have to setup a method to avoid the lexeme copy.
