### ISSUE TITLE
search and replace exits arbitrarily

### ISSUE THREAD

**Issue by eisbehr** [4coder-editor/4coder#132]
When doing a search&replace with a lot of places that get replaced, at some point the search and replace operation simply stops after hitting y. It then seem to fail more often when trying to finish the last replaces. Might have something to do with the buffer scrolling, maybe with what is and isn't in the visible range.

**Comment by 4coder-editor** [comment]
This was happening because the query replace was taking the buffer size at the beginning of the command and then using it to check if you had reached the end, so if the string replacement grows the buffer it would exit before reaching the end. Fixed in 4.1.3.
