### ISSUE TITLE
Change active panel (backwards) fails with certain panel configurations 

### ISSUE THREAD

**Issue by clearfeld** [4coder-editor/4coder#136]
If there is a setup like so
```
| - - - - - - - -| - - - - - -|
|        3       |            |
| - - - - - - - -|     4      |
|    2   |   1   |            |
| - - - - - - - -| - - - - - -|
```
change_active_panel will cycle through all panels (ie if you start at 1 it will go through the others and return on 1)

change_active_panel_backwards will cycle through the panels but will stop at the last one (ie if you start on 4 you can reach 1, but can't go back to 4)

**Comment by 4coder-editor** [comment]
Basic next/prev typo in the core implementation of get_view_prev, fixed in 4.1.2.
