### ISSUE TITLE
Backspace commands not working in group history records

### ISSUE THREAD

**Issue by bearbear2k** [4coder-editor/4coder#138]
When a group history record of multiple consecutive backspace commands is undone, the deleted characters come back out of order and in the wrong place. To be precise, the second character of the deleted string is moved to the end, and the entire string is shifted forward in the buffer by one character.

If the deleted characters were at the end of the buffer, the undo command causes the editor to crash (presumably due to writing past the end of the buffer).

Example:

Start: `0123456789xy`
After backspace commands: `xy`
After undoing the group record: `x0234567891y`

(4coder version 4.1.0)

**Comment by 4coder-editor** [comment]
Basically exactly as you described, when merging "backwards" strings, there was an error in the logic that was saving the wrong position as the starting point of the merged string. Fixed in 4.1.3.
