### ISSUE TITLE
Lexer cant be built in 4.1.1 because of missing "max()" function

### ISSUE THREAD

**Issue by Skytrias** [4coder-editor/4coder#141]
`
C:\Users\michael\Desktop\4coder\custom\lexer_generator\4coder_lex_gen_main.cpp(2703): error C3861: 'max': identifier not found
C:\Users\michael\Desktop\4coder\custom\lexer_generator\4coder_lex_gen_main.cpp(2714): error C3861: 'max': identifier not found`

seems like the `C:\Users\michael\Desktop\work\4coder\custom\4coder_base_types.h:271:9: #define max(a,b) (((a)>(b))?(a):(b))` got removed and the lex_gen_main.cpp was still using it.

This breaks lexer rebuilding in 4.1.1 by default and should be replaced by Max() which is used throughout the code base

**Comment by 4coder-editor** [comment]
Fixed by switching everything over to the correct Max macro. Fixed in patch 4.1.2.
