### ISSUE TITLE
toggle_show_whitespace has no effect

### ISSUE THREAD

**Issue by woodenToaster** [4coder-editor/4coder#144]
I would expect it to make whitespace characters visible, but it doesn't seem to do anything. Default theme and customization layer, beta 4.1.1.

**Comment by tebtro** [comment]
I think there is no implementation in the default render buffer hook.
But you can take a look at [my implementation](https://github.com/tebtro/4coder_custom/blob/master/custom/tebtro_draw.cpp) of it.

**Comment by 4coder-editor** [comment]
Added the implementation for this in 4.1.4.
