### ISSUE TITLE
Color sets should be based on user-supplied enums, not hard-coded

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#15]
Now that the renderer is opening up, 4coder probably can't keep dictating the set of allowable colors.  Users should supply their own color sets at startup time, and they could supply "names" to go with them to facilitate 4coder theme saving and interoperability.  4coder could define a set of "standard names" to help people share color sets between customization layers as necessary.

More care would need to be taken in the event of a "mergable" customization system for 4coder, where it loads multiple DLLs and they all play nice together.  This is probably something we want to move to eventually, so that people can ship upgrades as stand-alone modules that "plug in" in various ways.  If we wanted to plan for that, you'd have to "allocate" your colors, which is a little more of a pain in the butt, but it wouldn't be too onerous:

```
// In the global header for the plug-in
color_id GlobalMyTextColor;

// In the startup hook for the plug-in
GlobalMyTextColor = AllocateColor(app, "DefaultText");
```

And then you just use them as if they were enums, but of course they're actually dynamically handed out by the core.

\- Casey

**Comment by 4coder-editor** [comment]
Addressed this with a color table that the custom layer fills and submits to the core via a hook before each rendering phase.
