### ISSUE TITLE
Long paths are cut off when opening files etc.

### ISSUE THREAD

**Issue by tntmonty** [4coder-editor/4coder#151]
Long paths are cut off after they extend past the panel's width in "open file" etc. Could this be wrapped, or the earlier part of the path collapsed? I often end up with long path names at work, and it can be tough to ensure you're spelling things right when you can see what you're typing :).

**Comment by tntmonty** [comment]
Also struggling in search results etc for similar reasons. Maybe if in a project you could strip/replace the home directory? Maybe this is something I could already do with the customisation layer? I could maybe map a drive letter, but I'm less keen on doing that, and not sure how supported they are currently.

**Comment by 4coder-editor** [comment]
I addressed this by keeping the right side of the text field always in view, and cutting of the left side for now. Upgrade in 4.1.5.
