### ISSUE TITLE
The way paste history works is unsafe.

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#156]
4Coder saves to memory everything that is getting copied to the clipboard, even if it's done in a different context than intended - for example, it saves to memory unencrypted passwords copied from a password manager, or other possibly private data.
As discussed in discord, the default behavior should be capturing only things that were pasted to 4coder during the session, and possibly adding a "capture everything mode" that will fall back to the current behavior, while making it visually clear that everything is being captured.
It's also possible (as a bonus) to make "capture everything mode" time out after a specified period of time, so the user wouldn't need to remember to disable it manually when he finished his operation.

Either way the features that need to be supported are:
1. toggle and query the state of the "collect all clipboard events" mode
2. for when the "collect all clipboard events" mode is turned off, query for the most recent clipboard contents

**Comment by 4coder-editor** [comment]
This took some changes to the system layer which have to be applied to Mac still. The Windows changes, core changes, and default custom layer changes have been applied, and will be available in 4.1.4. The issue will be closed when the Mac version is updated too.

**Comment by 4coder-editor** [comment]
This is now implemented on every OS, fix in 4.1.4.
