### ISSUE TITLE
Missing functions in jump_to_definition

### ISSUE THREAD

**Issue by woodenToaster** [4coder-editor/4coder#158]
There are some (seemingly random) missing functions in the lister shown by `jump_to_definition`. For example, several string functions are present, but `string_match` is missing, even though it is defined in `4coder_base_types.cpp`. Also, `history_group_end` is present but `history_group_begin` is not, even though they are both defined in `4coder_helper.cpp`.

**Comment by aolo2** [comment]
This is [fixed](https://github.com/4coder-editor/4coder/issues/118) in 4.1.2.

**Comment by woodenToaster** [comment]
Thanks! Closing as duplicate of #118.
