### ISSUE TITLE
Support `indent_width` in virtual whitespace mode

### ISSUE THREAD

**Issue by 4lex1v** [4coder-editor/4coder#160]
It looks like the `indent_width` has no affect on the indentation size in virtual whitespace mode, it's fixed to 4 at the moment. It would be great to be able to change this to a different size.

**Comment by 4coder-editor** [comment]
I've added a variable `virtual_whitespace_regular_indent` to `config.4coder` that allows you to separately set the visual indent in virtual whitespace as a multiple of space-widths, this can be set to match the auto-indent width or it can be different, up to the user. Added in 4.1.4.
