### ISSUE TITLE
Changing drives in the file lister does not work (4.1.2)

### ISSUE THREAD

**Issue by M4zo** [4coder-editor/4coder#161]
With the 4.1.2 change `+ In file lister, typing a slash with a name for a folder that does not exist asks the user if they would like to create a folder` changing drives results in a `Create the folder d:\?` prompt. The desired behaviour would be to list the files in the d:\ directory.

To reproduce
1. run 4ed.exe
2. open file lister (default is `ctrl+o`)
3. backspace until an empty string is displayed at the `Open:` prompt
4. type a drive letter of your choice (e.g. `d:\`)

**Comment by exanimusfan** [comment]
Also if you delete the drive letter in the file lister query, you have to restart 4coder because it becomes impossible to open other files.

**Comment by rhoeberg** [comment]
+1 for both of these

**Comment by 4coder-editor** [comment]
Cause of this is pretty obvious, the file system lister logic didn't explicitly check if the text field is a drive, so it was treating the slash for the drive letter like a slash for a folder. Fixed in 4.1.3.
