### ISSUE TITLE
Unable to execute build.sh on macOS

### ISSUE THREAD

**Issue by Leon280698** [4coder-editor/4coder#162]
When I try to build my project on mac I get the following message in the \*compilation\* buffer:
```
sh: build.sh: command not found
exited with code 127
```

I fixed it by removing the elif case in ```standard_search_and_build_from_dir``` from 4coder_build_commands.cpp so that the command string is the same as on windows.

```cpp
#if OS_WINDOWS
        String_Const_u8 command = push_u8_stringf(scratch, "\"%.*s/%.*s\"",
                                                  string_expand(path),
                                                  string_expand(cmd_string));
#elif OS_LINUX || OS_MAC
        String_Const_u8 command = cmd_string;
#else
#error OS needs standard search and build rules
#endif
```

**Comment by 4coder-editor** [comment]
This wasn't giving me the same bug, but I also don't see any reason why they shouldn't all use the full path as in the Windows version, and it also worked just fine that way, so I've adopted this change in 4.1.3.
