### ISSUE TITLE
macOS: 4coder becomes unresponsive when an open file is changed by another program

### ISSUE THREAD

**Issue by Leon280698** [4coder-editor/4coder#163]
When a file that is opened in 4coder is modified by another program 4coder just stops accepting any keyboard or mouse input. Simply resizing the window makes it work again.

**Comment by 4coder-editor** [comment]
This was a bug in the implementation of a system that was supposed to signal the main loop, but since it was called from a background thread, it caused the run loop to stop instead. Fixed in 4.1.3.
