### ISSUE TITLE
lexer is generating tokens of different types with same pos.

### ISSUE THREAD

**Issue by tntmonty** [4coder-editor/4coder#165]
I noticed an issue while customising the virtual whitespace, and then realised it also happened in 4.1.2 unmodified, but only under very specific circumstances. A bit of the buffer was being returned as in a nest that it shouldn't have been, and that was due to it being at the start of two tokens of different types.

I tracked the issue down to 4coder_lex_gen_main.cpp, row3532.
```c++
fprintf(out, "token_list_push(arena, list, &token);\n");
fprintf(out, "emit_counter += 1;\n");
if (context != ActionContext_EndOfFile){
    fprintf(out, "if (emit_counter == max){\n");
    fprintf(out, "goto end;\n");
    fprintf(out, "}\n");
}
fprintf(out, "state.emit_ptr = state.ptr;\n");
fprintf(out, "}\n");
```
It looks as though the "state.emit_ptr = state.ptr" line should be directly below "emit_counter += 1". Changing that fixed my issues, and the issue in vanilla 4.1.2.

If that's a bad way to fix it, or I've got the wrong end of the stick, please let me know.
Cheers

**Comment by 4coder-editor** [comment]
Your assessment appears to be correct, logically. I should probably cook up a tester that asserts the output is consistent regardless of output chunk sizes to be sure, but I will probably adopt your suggested change in 4.1.3.

**Comment by tntmonty** [comment]
Thanks for looking at it. I'll e-mail you a file that has an example of a bad indent that I think is caused by this issue, just in case you find it useful.

**Comment by tntmonty** [comment]
Also noticed that in v1.4.2, 4coder_default_hooks.cpp#911 is badly indented if it's made to wrap after 'do_full_lex_async,'. This appears fixed with my changes, and doesn't require an edited file.
