### ISSUE TITLE
Crash when calling list_all_functions_all_buffers_lister while other lister is active.

### ISSUE THREAD

**Issue by andrewjhaman** [4coder-editor/4coder#166]
4coder 4.1.2 windows version crashes when trying to call list_all_functions_all_buffers_lister while in another lister. Tried with interactive_open_or_new or interactive_switch_buffer is active and command_lister and the crash occurs in all these cases. Crash does not occur if calling list_all_functions_all_buffers_lister from just a text buffer. The crash also does not occur if calling list_all_funtions_current_buffer_lister instead.

**Comment by 4coder-editor** [comment]
Okay. I've tried to recreate this without any success so far. So a few extra details:
1. How many code files do you have open when you do this?
2. How are you invoking list_all_functions_all_buffers_lister? Via a hot-key or through the command lister?

**Comment by andrewjhaman** [comment]
1. I have about 65 files open when I get the bug in my own codebase. I just tried it with the 4coder codebase open and it occurs there too. I have also tried with only default \*messages*, \*log*, \*keyboard*, and \*scratch* buffers open and it occurs there too.

2. I am invoking list_all_functions_all_buffers_lister via hot-key, the bug does not occur when invoking through the command lister. (I would guess because you have to close the 

I have just tried calling list_all_functions_all_buffers_lister via hot-key with the command lister, snippet lister and theme lister open and it occurs in that case too.

 Interestingly, when I try to use list_all_functions_current_buffer_lister with interactive_switch_buffer or interactive_open, nothing happens. That is, it stays on interactive_switch_buffer or interactive_open instead of going to list_all_functions_current_buffer_lister or crashing, so that could be a related issue.

Here is a gif of the crash occuring with the 4coder codebase open in 4coder's own directory, if that in any way helps.
![4coder_crash](https://user-images.githubusercontent.com/49106639/73711074-b8c23300-46d3-11ea-9cc2-6b0fbf85871f.gif)

**Comment by 4coder-editor** [comment]
Aha this was helpful. I tracked the issue down to the declaration of the list_all_functions_*_lister commands, which should have been declared with CUSTOM_UI_COMMAND_SIG instead of CUSTOM_COMMAND_SIG. The fix is in 4.1.3.
