### ISSUE TITLE
.h Include guard cuts off at number or underscore (at least)

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#167]
Creating a new .h files with a number or underscore in the name cuts off the include guard at the first char that isn't a a-z.
New file "r42_test.h" gets a "R" 
New file "testy_mcTestFace.h" gets a "TESTY"
New file "1234.h" gets a "" (nothing) 
etc.

**Comment by jim0** [comment]
Since I rewrote the function I'll just post it here.

`
#if 0 // I include these somewhere else.
inline b32 IsUpper(u8 C)        { return((C >= 'A') && (C <= 'Z')); }
inline b32 IsLower(u8 C)        { return((C >= 'a') && (C <= 'z')); }
inline b32 IsAlpha(u8 C)        { return(IsLower(C) || IsUpper(C)); }
inline b32 IsNumber(u8 C)       { return((C >= '0') && (C <= '9')); }
inline b32 IsAlphaNumeric(u8 C) { return(IsAlpha(C) || IsNumber(C)); }

inline u8 ToUpper(u8 C)         { if(IsLower(C)) { C -= 32; } return(C); }
#endif

BUFFER_HOOK_SIG(reidar42_new_file){
   
   Scratch_Block scratch(app);
   String_Const_u8 file_name = push_buffer_base_name(app, scratch, buffer_id);
   if(!string_match(string_postfix(file_name, 2), string_u8_litexpr(".h"))) { return(0); }
   
   List_String_Const_u8 guard_list = {};
   u8 CharPrev = 0;
   for(u64 i = 0; i < file_name.size; ++i){
      u8  CharOut[2] = {};
      u64 CharOut_size = 1;
      
      u8  CharIn = file_name.str[i];
      if((CharIn == '.') || (CharIn == '_')){ CharOut[0] = '_'; } else 
      if(IsAlphaNumeric(CharIn)) { 
         // if(CharPrev && IsLower(CharPrev) && IsUpper(CharIn))
         if(CharPrev && ((IsLower(CharPrev) && IsUpper(CharIn)) || 
                         (IsUpper(CharPrev) && IsLower(CharIn)))){
            CharOut[0] = '_'; 
            CharOut[1] = ToUpper(CharIn);
            CharOut_size = 2;
         } else {
            CharOut[0] = ToUpper(CharIn); 
         }
      } 
      
      String_Const_u8 part = push_string_copy(scratch, SCu8(CharOut, CharOut_size));
      string_list_push(scratch, &guard_list, part);
      CharPrev = file_name.str[i]; 
   }
   String_Const_u8 guard = string_list_flatten(scratch, guard_list);
   
   Buffer_Insertion insert = begin_buffer_insertion_at_buffered(app, buffer_id, 0, scratch, KB(16));
   insertf(&insert,
           "#if !defined(%.*s)\n"
           "#    define  %.*s\n"
           "\n"
           "#endif // %.*s\n",
           string_expand(guard),
           string_expand(guard),
           string_expand(guard));
   end_buffer_insertion(&insert);
   
   return(0);
}
`
Please excuse the superficial changes :)

**Comment by 4coder-editor** [comment]
I have adopted a similarly effective fix for this routine in 4.1.3.
