### ISSUE TITLE
Random memory in current_project

### ISSUE THREAD

**Issue by tebtro** [4coder-editor/4coder#169]
Can't use the current projects whitelist or blacklist.
Because we are passing a scratch block to `parse_project`.
Maybe passing the global project arena would be the right thing.

So in `set_current_project` there is a `project_deep_copy` beeing called, but I don't think that everything is really copied.

**Comment by 4coder-editor** [comment]
This was happening due to a bug in the deep copy for projects. Fixed in 4.1.4.
