### ISSUE TITLE
If PreprocessorBody token follows an if, its indentation can be incorrect.

### ISSUE THREAD

**Issue by tntmonty** [4coder-editor/4coder#170]
The following code shows a non-ideal auto-indent (note to see it in 4coder you have to have virtual whitespace turned off).
```C++
int main()
{
	switch(arg)
	{
		case one:
		{
#ifdef
			if(true)
    #endif
			do_something();
		}
	}
}
```

In 4coder_auto_indent.cpp, get_indentation_array(), if you move the lines
```C++
                if (in_unfinished_statement && !ignore_unfinished_statement){
                    this_indent += indent_width;
```
into the scope above, so that it isn't hit for PreprocessorBody, it will fix the problem, but not sure if this is the best way.

**Comment by tntmonty** [comment]
Correct it's to its.

**Comment by 4coder-editor** [comment]
This suggestion makes sense, it is integrated in 4.1.3.
