### ISSUE TITLE
How far the view scrolls to keep cursor inside view is uncustomizable 

### ISSUE THREAD

**Issue by GreyDodger** [4coder-editor/4coder#174]
also it'd be nice if the buffer would begin to scroll even when you're not totally outside the view, e.g. you're scrolling downwards and 4coder always tries to have your cursor 4 or so lines up from the bottom

**Comment by tntmonty** [comment]
It would be nice to be able to scroll the view while searching so you can look around the current match without stopping the search as well.

**Comment by 4coder-editor** [comment]
I added an API for setting the margin and the push in values that the camera uses when moving to the cursor, and I used it to extend the margin when doing an isearch. Features in 4.1.6
