### ISSUE TITLE
get_indent_info_range() counts '\t' as a width of 3 now.

### ISSUE THREAD

**Issue by tntmonty** [4coder-editor/4coder#176]
get_indent_info_range() counts '\t' as a width of 3 now, which means that more lines are auto-indented than need to be. This is new to v4.1.3, and is because tabs don't go through both the space and tab logic now (4coder_helper.cpp#1222). Changing tab_additional_width to tab_width fixes the issue.

I've noticed this as I'd accidentally got indent_with_tabs set differently, and it updated all tabs to spaces, but wouldn't change them back.

**Comment by tntmonty** [comment]
I meant to say it counts them as tab_width - 1 of course, not always 3.

**Comment by 4coder-editor** [comment]
Aha, yes clearly a problem. Fixed in 4.1.4.
