### ISSUE TITLE
load_theme_current_buffer on non theme file

### ISSUE THREAD

**Issue by clearfeld** [4coder-editor/4coder#177]
When you run the command load_theme_current_buffer on a non theme file, the entire view will become purple.

**Comment by 4coder-editor** [comment]
I've added a sanity to check to this command so that the theme is only saved and applied if there aren't any errors in parse, and not to many blank/undefined spots in the resulting color palette. Change in 4.1.4.

**Comment by cristeigabriel** [comment]
an issue very similar to this seems to persist in 4.1.8. tinkering with `load_theme_*` commands when current folder is 4coder's dir seems to, at times, load non-theme files to `themes_list` (example: bindings). loading any of these will just cause the same issue as mentioned in the OP.
