### ISSUE TITLE
Margins?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#18]
At the moment, I don't see any way to have user-definable margins for windows.  You want to be able to do things like add a line number display on the left side of a view, but as far as I can tell, there's no way to inform 4coder that you intend to take n pixels on the side of the window and have it properly account for that when it does layout.  The broader issue here might be "let's give the custom layer control over text layout boxes in general", and that's fine too, but if that's not coming for a while, allowing the user to dynamically set left/right/top/bottom margins for their windows might be a good interim measure.

\- Casey

**Comment by 4coder-editor** [comment]
After thinking about this for a while I decided to put this in a callback that is called per-view during rendering to determine the rectangle in which the buffer will be rendered.  Trying to manually 'set' the margin was a pain, as it would force me to track down all the places where I change something that would effect what belongs in the margin.

I moved the file bar and query bar rendering into the render caller.
