### ISSUE TITLE
Using close_panel on the build window makes no small panels open.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#182]
Version: 4.1.3

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Run a build, 
2. alt+x
3. close_panel

**Description of the Result**
Stops small panels from opening. 

**Additional notes**
Even tho the window doesn't pop up it seems like the work gets done in the background. (the work ex. the build)
As I write this I'm wondering if it only happens if you build in a small panel.
Workaround is running close_build_panel (even if its not visible). 
 

**System**
OS: W10

**Comment by 4coder-editor** [comment]
Fixed by making the functions that manipulate the footer panel check if the bound view exists rather than just checking if it is zero. Fix in 4.1.4.
