### ISSUE TITLE
Cannot exit program while querying user (ie I-Search, List All Locations etc)

### ISSUE THREAD

**Issue by 2BJones** [4coder-editor/4coder#183]
Version: 4.1.3

**Repro Steps**
1) Press ctrl-t to initiate I-Search
2) Try to exit program with alt-f4 or the corner X

**Description of the Result**
It does not exit.

**Additional Notes**
No customizations used.  Seems to happen on any function that queries the user.

**System**
OS: *Windows x64*

**Comment by 4coder-editor** [comment]
Fixed by adding command dispatches to the isearch and query_user_general functions. Fix in 4.1.4.
