### ISSUE TITLE
MinorBugButABug: Mouse button release outside of a 4Coder window doesn't register.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#184]
Version: 4.1.3

**Repro Steps (Including a snippet of any potentially related customization code)**
1- Clicking and holding left mouse button on a 4Coder window, 
2- Drag out of the window and let go, 
3- Bring the mouse back into the windows and observe. 

**Description of the Result**
You'll be in a state of holding the mouse button down without holding the mouse button down, ex. the input_cursor follows your mouse_cursor around.

**Additional notes**
Not a huge deal but in case you didn't know.
(the workaround is just clicking inside the window)

**Comment by 4coder-editor** [comment]
Was missing the necessary SetCapture calls, fixed in 4.1.5.
