### ISSUE TITLE
Once-Per-Frame, Post-View Render Hook

### ISSUE THREAD

**Issue by ryanfleury** [4coder-editor/4coder#185]
A hook that is called once per frame to do rendering on top of all views would be really useful, since sometimes it's useful to do rendering that isn't associated with a particular panel (tooltips and such).

Alternatively, maybe just a single rendering hook for all rendering that does its own looping through panels and does whatever it wants for each one? That'd be a relatively breaking API change though so I could understand why that wouldn't be preferable.

**Comment by clearfeld** [comment]
I'm adding my vote for the alternative listed. Having a render loop that calls a specific render function for each panel would be really nice, especially when trying to create special purpose views.

**Comment by 4coder-editor** [comment]
This hook was included in 4.1.4.
