### ISSUE TITLE
Single line comments with line-continuation characters in them are not correctly drawn

### ISSUE THREAD

**Issue by TheSandvichMaker** [4coder-editor/4coder#186]
This is an exceptionally obscure thing, but it turns out in C++, the line continuation character '\' will continue single line comments onto the next line, like so:
https://i.imgur.com/cnaBkMC.png

I discovered this today because vim highlights these comments correctly, and I noticed 4coder doesn't.
It's enough of an obscure feature that it even has its own compiler warning in MSVC, but to be exactly correct it would be nice to support it.

**Comment by 4coder-editor** [comment]
Turned out to be a nice and easy addition to the C++ lexer. This feature is in 4.1.5.
