### ISSUE TITLE
MacOS touchpad scrolling is too fast.

### ISSUE THREAD

**Issue by umurgdk** [4coder-editor/4coder#187]
Version: 4.1.X

**Repro Steps**
Just scroll any buffer using macbook touchpad or magic mouse.

**Description of the Result**
Even small scrolls resulting in huge scrolls in the buffer.

**Additional notes**
This is probably caused by some sort of smooth scrolling feature defined by 4coder. But on macOS scroll events are continues and scroll acceleration and deceleration are handled by operating system **if apple trackpad or magic mouse is used**. I believe disabling that smooth scroll functionality all together on macOS platform layer might solve the problem already.

**System**
OS: macOS Catalina: 10.15.3

**Comment by 4coder-editor** [comment]
This was a bug in how the scroll events were stuffed into the input structure to 4coder that was discarding Macs suggested ∆y values. Fixed in 4.1.4.
