### ISSUE TITLE
Pasted code that gets indented triggers animation of the incorrect characters.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#188]
Version: 4.1.3

**Repro Steps (Including a snippet of any potentially related customization code)**
Paste code where it would be indented automatically.

**Description of the Result**
see the characters that get their colors animated are (offset by the indentation length of the indentation?)

**Additional notes**
If I paste something on a line that gets auto-indented the wrong characters get the flashing color animation.

**System**
OS: Windows10

**Comment by 4coder-editor** [comment]
To address this I added a fixup routine to the edit range hook that fixes the positions of all the fade ranges whenever an edit comes in. Fix is in 4.1.5.
