### ISSUE TITLE
Date and Time functions

### ISSUE THREAD

**Issue by iamriles** [4coder-editor/4coder#190]
Add a multi platform solution to the 4coder api of getting the date and time for the local system.

- Suggestion: date formatting use an integer in with yyyymmdd  ordering too allow for simple user level parsing and sorting.

- Suggestion: time formatting  use and integer with hhmmss for the same reasons listed above.

**Comment by 4coder-editor** [comment]
I've added a call for getting UTC date time, calls for converting UTC and local time, and a date time string formatting system.

**Comment by iamriles** [comment]
awesome

**Comment by 4coder-editor** [comment]
Full Mac and Linux implementations are now in as well.
