### ISSUE TITLE
Bool color in theme is not working

### ISSUE THREAD

**Issue by Quadx117** [4coder-editor/4coder#194]
Version: 4.1.3

**Repro Steps (Including a snippet of any potentially related customization code)**
Changing the color of the defcolor_bool_constant variable in any theme file.

**Description of the Result**
The color of the bool constants stays the same as the int constants

**Additional notes**
Similar to issue #193 

**System**
OS: *Windows 10*

**Comment by 4coder-editor** [comment]
Simple matter of a flaw in the logic mapping token kind -> color palette slot. Fixed in 4.1.5.
