### ISSUE TITLE
The key bindings override inherited key maps, even when them match is not full

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#199]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
In whatever function you are binding you keys:
```c
MappingScope();
SelectMapping(mapid_global);
Bind(move_up_to_blank_line, KeyCode_Up, KeyCode_Control);

SelectMappng(mapid_file);
ParentMap(mapid_global);
Bind(move_up, KeyCode_Up);
```
**Description of the Result**
Pressing Up+Control always result in triggering move_up instead of move_up_to_blank_line

**Additional notes**

**System**
OS: *Windows 10*

**Comment by 4coder-editor** [comment]
I have changed to first scanning all maps for strict matches, before scanning for loose matches. Fix in 4.1.5.
