### ISSUE TITLE
Allow treating modifier keys as actual keypresses?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#20]
For those of us who use modal configs, it'd actually be nice to have some keys (like control) operate as regular keys rather than modifiers.  It'd be nice if there was some way to tell 4coder to stop ignoring keypresses of control, alt, etc., and instead allow binding of those to actual functions.

This may already be possible, I just wasn't sure how to do it.

\- Casey

**Comment by cmuratori** [comment]
So, I tried hacking this in myself.  It _seems_ like it "just works" if you remove the "break" statement from the win32 keyboard processing of CTRL/ALT/SHIFT and let it fall through to the non-modifier section, and then add the CTRL/ALT/SHIFT keys to the keycode table.

So this is probably a pretty easy one to do at least on Windows.  Mac and Linux may be harder, I don't currently build on the those platforms.

\- Casey

**Comment by 4coder-editor** [comment]
Nice!  I was able to get this working in just a couple minutes, thanks for the tip.  I am pretty sure this will work on the other OSes without too much hassle, so I'll leave this open until I've got it working everywhere.
