### ISSUE TITLE
Can't run 4.1 in Linux with Wayland

### ISSUE THREAD

**Issue by absrd** [4coder-editor/4coder#200]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
Run

**Description of the Result**
`Fatal Error: Error getting XKB keyboard details.`

![2020-03-11T15:42:21+01:00](https://user-images.githubusercontent.com/5443936/76429984-13743c00-63b0-11ea-8c74-80e91db431d5.png)

**Additional notes**
This was not an issue in 4.0
**System**
OS: Void Linux, Linux 5.4.24_1, Wayland
Graphics Driver (for graphics bugs): *Driver*

**Comment by Pilzschaf** [comment]
Same problem for me. I did a quick ltrace and it seems that the call to XkbGetKeyboard returns 0 on Wayland. I actually found a similar issue in glfw which suggests switching to XkbGetMap instead. https://github.com/glfw/glfw/issues/389

**Comment by baines** [comment]
Should be fixed in the next release.
It has been changed over to XkbGetMap and seemed to work under Weston.

**Comment by 4coder-editor** [comment]
I am not sure I can reproduce this, but I will tentatively close this issue on @baines 's recommendation.

If this is still an issue in the next build (4.1.5) please re-open.
