### ISSUE TITLE
The command lister crashes 4coder when there are too many key bindings.

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#201]
Version: 4.1.4

**Description of the Result**
The command lister crashes when I have more than a certain quantity of key bindings.
Exception:
![image](https://user-images.githubusercontent.com/5497895/76458603-77fcbe80-63e3-11ea-9f36-b57ba9dd2a03.png)
Call stack:
![image](https://user-images.githubusercontent.com/5497895/76458282-fd33a380-63e2-11ea-81b1-36fb8d48b298.png)
![image](https://user-images.githubusercontent.com/5497895/76458742-b09c9800-63e3-11ea-9858-c06febf0eeb0.png)

**Additional notes**
My layer is available [here](https://gitlab.com/xdnicoco/4coder_modal) in case you can't reproduce it yourself.

**System**
OS: *Windows 10*

**Comment by 4coder-editor** [comment]
This issue was related to two arena pointers that both referenced the same arena. When one reset it's memory, the other lost memory that was still supposed to be usable. Fixed in 4.1.5.
