### ISSUE TITLE
Ability to render tabs with width different from indentation size

### ISSUE THREAD

**Issue by XrXr** [4coder-editor/4coder#202]
I work in https://github.com/ruby/ruby which uses mixed tabs and spaces. The code is indented 4 spaces but each tab is supposed to equal 8 spaces. Is there a good way to render sources files in that repo properly in 4coder?  Take a look at https://github.com/ruby/ruby/blob/master/ruby.c for  an example. GitHub renders it correctly but 4coder doesn't, in the default configuration anyways.

Side note, Vim and Emacs are able to do it, which is why this has been the policy thus far in that repo thus far.

**Comment by 4coder-editor** [comment]
To address this I added a default_tab_width to config.4coder that sets the width of tabs as a multiple of spaces. Modifying this setting changes both the rendering, and auto-indenter's understanding of a tab's width. The feature is in 4.1.5.
