### ISSUE TITLE
4editor is inresponsive after creating file

### ISSUE THREAD

**Issue by thinkimlazy** [4coder-editor/4coder#204]
This bugs is on fresh unzipped new 4editor both demo and bought version

Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Create new cpp file (i.e. ~/qwe.cpp)
2. start typing `#i`

**Description of the Result**
Application is irresponsive

**Additional notes**

**System**
OS: Mac Catalina

**Comment by thinkimlazy** [comment]
Also it's irresponsive when I try to create file:
Cmd+n.
New file: /Users/r.ivanov/lmao.cpp
And it's crashed

**Comment by Leon280698** [comment]
Can confirm. I also get this sometimes when I move a line up and down again with Alt->Arrow keys. Only seems to affect files that are treated as code.

**Comment by 4coder-editor** [comment]
This was related to another issue with `system_acquire_global_frame_mutex` which is fixed in the next build 4.1.5.
