### ISSUE TITLE
Scrolling with the mouse wheel is very slow on macOS

### ISSUE THREAD

**Issue by Leon280698** [4coder-editor/4coder#209]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
Open a buffer with enough lines and use mouse wheel to scroll up or down.

**Description of the Result**
Scrolling is super slow and only works when turning the mouse wheel fast enough.

**Additional notes**
Scrolling with the trackpad on my Macbook seems fine.

**System**
OS: macOS Catalina 10.15.3

**Comment by 4coder-editor** [comment]
It appears we were not handling the "NO" case described here (https://developer.apple.com/documentation/appkit/nsevent/1535387-scrollingdeltay?language=objc).

I am not sure because I can't test with a mouse on my Mac, but I believe this will be better in 4.1.5.
