### ISSUE TITLE
clean_all_lines does not clean lines that only contain whitespace

### ISSUE THREAD

**Issue by Leon280698** [4coder-editor/4coder#210]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Create a new line only containing whitespace characters.
2. Execute clean_all_lines

**Description of the Result**
Line is not cleaned.

**Additional notes**
I fixed it for my custom layer here: https://github.com/Leon280698/4coder_leon/blob/b5423615083be312f9bdacf54acc13b808355d2a/4coder_leon.cpp#L79

**Comment by tebtro** [comment]
This was a workaround for a previous bug (crush): [Issue 146](https://github.com/4coder-editor/4coder/issues/146)
I think this bug was then fixed in 4.1.4
But yeah, most would probably want empty lines to also get cleaned, I guess.

**Comment by 4coder-editor** [comment]
Well if you're using clean_all_lines and then auto-indenting, it will just put the whitespace right back in - I guess I didn't realize this would be a preference. However I have just gone ahead and split the `clean_all_lines` commands into two, the original removes blank lines and the new `clean_trailing_whitespace` leaves blank lines. This change is in 4.1.5.
