### ISSUE TITLE
Cursor Without Rounded Corners

### ISSUE THREAD

**Issue by Noah11012** [4coder-editor/4coder#211]
Low priority obviously, but could you add an option in the config.4coder file or somewhere else to get the old cursor. The simple rectangle without any rounded corners. Thanks!

**Comment by 4coder-editor** [comment]
I've added a cursor_roundness variable which, when set to zero, will have the effect you're asking for. For good measure I also through in a lister_roundness variable, so that if you're a super big anti-fan of rounded rectangles, you can disable them there too. The new features are in 4.1.5.

**Comment by Noah11012** [comment]
Wow! Thanks a lot! Will definitely be using that when the new version comes out!
