### ISSUE TITLE
fullscreen crash on mac

### ISSUE THREAD

**Issue by simonwashere** [4coder-editor/4coder#213]
Version 4.1.4

Calling with the -F flag to start in fullscreen crashes every time on my mac.

Mac mini (2018)
macOS 10.15.4 (19E287)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1452]

VM Regions Near 0x10:
--> 
    __TEXT                 000000010f787000-000000010f861000 [  872K] r-x/rwx SM=COW  /Users/USER/*

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   4ed                           	0x000000010f78ba75 -[FCoder_View updateLayer] + 37
1   com.apple.AppKit              	0x00007fff2ff4c407 _NSViewUpdateLayer + 98
2   com.apple.AppKit              	0x00007fff2ff4bcbc -[_NSViewBackingLayer display] + 501
3   com.apple.QuartzCore          	0x00007fff3e6c4469 CA::Layer::display_if_needed(CA::Transaction*) + 757
4   com.apple.QuartzCore          	0x00007fff3e6a2716 CA::Context::commit_transaction(CA::Transaction*, double) + 334
5   com.apple.QuartzCore          	0x00007fff3e6a1304 CA::Transaction::commit() + 644
6   com.apple.AppKit              	0x00007fff307b5283 -[_NSEnterFullScreenTransitionController start] + 43
7   com.apple.AppKit              	0x00007fff30397d40 -[_NSWindowEnterFullScreenTransitionController start] + 367
8   com.apple.AppKit              	0x00007fff3090a553 -[_NSFullScreenSpace(Transitions) startTransition:] + 133
9   4ed                           	0x000000010f78f9f6 main + 9782
10  libdyld.dylib                 	0x00007fff6cb2acc9 start + 1

**Comment by 4coder-editor** [comment]
Looks like it's not allowed to toggle fullscreen before the run loop starts or something. Fixed by just delaying the toggle to the update function. Fix in 4.1.5.
