### ISSUE TITLE
load_project crash

### ISSUE THREAD

**Issue by jmrico01** [4coder-editor/4coder#215]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Create an empty folder
2. Place this `project.4coder` file inside it: [project.zip](https://github.com/4coder-editor/4coder/files/4462265/project.zip)
3. Open 4coder, Ctrl+O, navigate to folder, open `project.4coder`
4. Alt+X, run command `load_project`, 4coder crashes

**Description of the Result**
4coder crashes, closes immediately

**Additional notes**
The culprit here seems to be the un-bracketed value after `.cmd = `:
```
command_list = {
{
	.name = "test",
	.out = "*test*", .footer_panel = true, .save_dirty_files = false, .cursor_at_end = true,
	.cmd = "test",
},
};
```
For people unfamiliar with the `project.4coder` format, this seems like a reasonable thing to do - would be good to get an error in `*messages*` in this case.

**System**
OS: *Windows 10 Home*
Graphics Driver (for graphics bugs): *N/A, I think*

**Comment by 4coder-editor** [comment]
This was just a mental typo. Fixed in 4.1.5, and I improved the format of project errors just slightly to set the apart more in the messages buffer, just for good measure.
