### ISSUE TITLE
Scroll resets selection

### ISSUE THREAD

**Issue by jmrico01** [4coder-editor/4coder#216]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Set mode to `notepad-like`
2. Using the mouse, hold click and drag to form a selection, don't release click
3. Scroll up or down, the selection will reset

**Description of the Result**
Selection resets on scroll, in `notepad-like` mode.

**Additional notes**
Not sure if this is how the cursor/mark paradigm is meant to work, or if this even makes sense to think about there. Here's a speedy gif of it happening:

![ezgif-2-ea51f1b1af50](https://user-images.githubusercontent.com/11249051/79083169-69633900-7cfa-11ea-9642-10edbc896598.gif)

**System**
OS: *Windows 10 Home*
Graphics Driver (for graphics bugs): *Probably N/A*

**Comment by 4coder-editor** [comment]
Ahh thanks for this one. It's hard to know what little details aren't working in notepad-like mode since I'm not a regular user of it. This was a simple fix, just needed to set the scrolling commands to not snap the mark to the cursor. Fixed in 4.1.5.
