### ISSUE TITLE
Why aren't buffer dirty states composable?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#22]
Right now, a buffer can either be marked as having changed in 4coder _or_ as having been changed on disk, but not both.  This doesn't actually model the problem, since a buffer could easily have been changed _both_ in 4coder _and_ on disk, and certain custom layer implementations might want to know that so they can take the appropriate action.  So I think we want the dirty state to change to a dirty flags field, and allow OR'ing together of multiple of these states at once?

\- Casey

**Comment by 4coder-editor** [comment]
The core now does this correctly. There may be a few lingering problems with how this is treated in mine and everyone's custom layer.
