### ISSUE TITLE
bad AZERTY-QWERTY translation using modifier keys Ctrl and Alt 

### ISSUE THREAD

**Issue by RemiCecchinato** [4coder-editor/4coder#222]
Version: 4.1.4

With an AZERTY keyboard, key combinations Ctrl+... and Alt+... does not work properly.
For example when I type Ctrl+Z, instead of undoing a z is added to the buffer. To undo I have to
press Ctrl+W (the Z ans W keys are switched between AZERTY and QWERTY keyboards).
Every keybinding is messed up in that way.

I am running linux.

**Comment by baines** [comment]
Yeah the Linux layer was set up so the `KeyCode` APIs are based around physical key position - They'll always be in QWERTY position regardless of layout.

The `Text` APIs on the other hand are based on the real key symbol, so it should be possible to bind e.g. Ctrl-Z with the `Text` API and have it switch around with your keyboard layout.

I'm not sure what the state of the default bindings is (if they use the `KeyCode` or `Text` approach).

**Comment by RemiCecchinato** [comment]
Thanks for your reply.

Do you know how I can switch these two APIs ? I looked around but wasn't able to find.

**Comment by baines** [comment]
I had a quick look at the custom layer stuff, and unfortunately didn't see an easy way to bind keys based on text input.

The easiest workaround I could see is editing `custom/4coder_default_map.cpp` and changing the KeyCodes to what they would be in QWERTY...

Another kinda-hacky option would be to modify the `write_text_input` function in `4coder_base_commands.cpp`, and check if `insert` matches your key.
It looks as though the `Text_Insert` event doesn't provide modifier keys though. There is a separate `system_get_keyboard_modifiers` function that could maybe be used to get them, but I haven't tested this idea.

There might be a proper/simpler way to do it, but i'm not super familiar with the custom layer side.

**Comment by RemiCecchinato** [comment]
Thank you, I'll probably go for the first option for now just for simplicity.

**Comment by 4coder-editor** [comment]
Key stroke bindings are intentionally encoded independent of keyboard language.
