### ISSUE TITLE
Crash when typing in a parenthesis

### ISSUE THREAD

**Issue by jmrico01** [4coder-editor/4coder#224]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**

Reproduced on 2 different Windows 10 machines, one of them with no custom layer built.
1. Set 4coder mode to `notepad-like`
2. Create a C++ file with the following contents and save it
```cpp
{
    {
        (hello);
    }
}
```
3. Select the word `hello` and only the word `hello`
4. Type in an opening parenthesis (shift+9)

**Description of the Result**

CRASH! At least for me

**Additional notes**

**System**
OS: Windows 10 Enterprise
Graphics Driver (for graphics bugs):

**Comment by 4coder-editor** [comment]
This was a bug with the write-and-auto-indent command that didn't properly account for the fact that notepade-like mode can replace a range when doing a normal insertion. Fixed in 4.1.5.
