### ISSUE TITLE
GlyphFlag_Rotate270 for draw_string_oriented

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#227]
I have added scope annotations similar to what Casey has in the handmade hero streams. draw_string_oriented only allows to draw string with glyph rotated 90° (base line to the left, "normal" text growing toward the bottom of the screen). I would like to test drawing the text with glyph rotated 270° (base line to the right, "normal" text growing toward the top of the screen). Unless I'm mistaken there is no way to do that at the moment.

**Comment by 4coder-editor** [comment]
Sounds good, but I think just basing the text rotation on the base-line delta makes more sense. I've deprecated the flags entirely, now all you need to rotate text at any angle is pass in a unit vector for the base line. Feature in 4.1.6.
