### ISSUE TITLE
Missing icons in title bar and alt-tab menu on Windows 7

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#228]
Version: 4.1.4

4coder uses the default application icon in the window title bar and in the alt tab menu instead of the "green 4". The icon displays correctly on the exe file and in the task bar. This happens both with the classic theme and default aero theme. Previous version (4.0.x) display the icons correctly.

**System**
OS: Windows 7 ultimate 64bit

**Comment by 4coder-editor** [comment]
Fixed in 4.1.6.
