### ISSUE TITLE
Buffers should know their original name as well as their canonical name

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#23]
At the moment, buffers only remember their full canonical name.  The canonical name is obviously best for 4coder's internal tracking, to make sure it doesn't open the same file twice under two different names.  But from the user's perspective, they may also want to know the path of the buffer as they originally entered it.

To be more specific, in my buffer lister, I list the name _and_ the filename of the buffer.  But since the filename is canonical, it doesn't match the actual filename I loaded.  Typically I load something like "w:/handmade/code/handmade.cpp", and I'd like to see it listed that way.  But since w: is a substitution, what I actually see in 4coder is "c:/work/handmade/code/handmade.cpp".

So I would suggest we augment the buffer to have both the originally requested filename _and_ the canonical filename, so that the custom layer can use the original one when displaying the path to the user.

\- Casey

**Comment by 4coder-editor** [comment]
I added a buffer_get_base_name that takes a buffer_id and returns the base name (i.e. the original name) of the buffer, via the normal string return mechanism which attempts to append the name onto a String struct passed in by pointer.
