### ISSUE TITLE
Access to changes done by buffer_history_set_current_state_index

### ISSUE THREAD

**Issue by LagMeester4000** [4coder-editor/4coder#231]
I'm implementing LSP for autocompletion. The protocal lets you send diffs of the edits you did to a document. It is working for the most part, but when I undo/redo it desyncs. If I had access to the changes done to the document when the history state is set, I could make it fully deterministic (afaik).
Another change that would help is the ability to swap the buffer_replace_range function with my own (though maybe I could do that with the vtable thing), as right now I have just replaced every instance of it.

**Comment by 4coder-editor** [comment]
Can you achieve this with some work in the buffed edit range?

```
typedef i32 Buffer_Edit_Range_Function(Application_Links *app, Buffer_ID buffer_id,
                                       Range_i64 new_range, Range_Cursor old_range);
```

```
internal
BUFFER_EDIT_RANGE_SIG(name){
}
```

From there you should be able to call:
http://4coder.net/docs/custom_api_index.html#buffer_history_get_current_state_index
http://4coder.net/docs/custom_api_index.html#buffer_history_get_max_record_index
http://4coder.net/docs/custom_api_index.html#buffer_history_get_record_info

To figure out if you're seeing a history change or a fresh edit and in the case of history edits you should be able to use the index plus the change ranges to figure out what side of the history record gives the diff?

That might not be enough information. What if I extended this hook with a signed integer for:
1 -> redo
0 -> normal edit
-1 -> undo
Would that be enough information then?

**Comment by LagMeester4000** [comment]
Thanks! I tried it out and it works well. I did not have the version with the Range_Cursor argument yet, but it comes in handy because I need to send the range as (line, colon).

I don't think extra history information is needed. The language server treats an undo as a new version of the file.
