### ISSUE TITLE
MacOS Enter or Tab Not Working

### ISSUE THREAD

**Issue by hunterkepley** [4coder-editor/4coder#234]
Version: 4.1.5

**Repro Steps**

Open 4Coder, try to press Enter (return) or Tab

**Description of the Result**

No newline or tab is created, nothing happens

**Additional notes**

Tried using fn + enter/return and fn + tab just in case it was something weird on my Macbook's keyboard, did not fix.

**System**
OS: *macOS Catalina 10.15.4*

**Comment by 4coder-editor** [comment]
Unfortunately these don't get generated like normal text events by Mac's textInsert API, but it's not hard to just generate those events with a special case. Fixed in 4.1.6.
