### ISSUE TITLE
Revert does not work

### ISSUE THREAD

**Issue by Trisher** [4coder-editor/4coder#235]
Version: 4.1.5

**Repro Steps (Including a snippet of any potentially related customization code)**
When trying to revert text using CTRL+Z nothing happens. As I'm using a german keyboard layout I also tried CTRL+Y but it has the same result. 4.1.4 works.

**System**
OS: Windows 10 x64 (german keyboard layout)

**Comment by 4coder-editor** [comment]
Are you used to hitting Z in the location that types Z on a German keyboard for undo? I have been unsure if key-combos should be bound by their physical key or should move around to keep the letters lined up with the language. In this version on Windows I thought I fixed it by putting the key combos in the physical location.

**Comment by Trisher** [comment]
Yes on a german keyboard Z and Y are inverted to the english layout. I have to correct my reproduction steps as CTRL+Y acutally works as undo and CTRL+Z works as redo, so it is simply inverted on my layout. What may make it even worse is that I have the language settings of windows set to English.

**Comment by 4coder-editor** [comment]
I see. So just to be 100% clear, the key in the bottom left corner for you is Y and it does undo?

Like I said it's currently setup to use physical layout to bind commands not character translations. If the other way is the way things usually work I'll just switch it back. I may have been confused about what was more helpful.

**Comment by Trisher** [comment]
Yes the bottom left key is Y, but it is redo and the key next to T is Z witch is undo.

**Comment by 4coder-editor** [comment]
I'm sorry that's a little unclear to me. Can you be specific about which one you'd want them to be? The bottom left key is Y and you want it to be redo but it's undo right?

**Comment by Trisher** [comment]
Yes we use CTRL+Z (which is the key next to T) to undo things but in 4.1.5 it is redo and CTRY+Y (bottom left) is used to redo which is undo in 4.1.5.
4.1.4 did it right.

**Comment by 4coder-editor** [comment]
I am addressing this by making the physical key codes a mode that can be toggled and making language arranged key codes the default.

**Comment by Trisher** [comment]
Sounds good, thanks for 4coder and the fix :)

**Comment by CaptainTimberTim** [comment]
May I ask when this change will be available?
The current version with this _bug_ is not really usable for user with a QWERTZ keyboard. IMO. 
And I would really like to use the new version. 

Keep up the good work!

**Comment by Incognitas** [comment]
From what I see here, the bug is also present on windows 10 x64 with french layout (AZERTY keyboard).
Ctrl+Z just... inserts Z, 
Ctrl+comma does nothing etc.
So right now, I can confirm this is pretty unusable.

Keep up the good work though !

**Comment by mrmixer** [comment]
@CaptainTimberTim @Incognitas It's not really a bug. In 4.1.5 you need to use the KeyCodes as if they were the position of the physical key on a QWERTY US keyboard. For example the key next to tab in QWERTY is Q so now you always use KeyCode_Q to bind the key next to tab, independently of the keyboard layout set in Windows. It's a bit confusing to figure out which keycodes to use, but you can use the display_key_codes command which you probably already used to figure some key codes out.

**Comment by Incognitas** [comment]
@mrmixer thanks for the heads up, but it is just a noticeable change compared to the previous version and I am not sure it was the intended behaviour. 
Ok if I do Ctrl+W instead of Ctrl+Z on my azerty keyboard it would work as intended (aka undo). So I just have to remap my shortcuts in my custom layer (which I did), but pointing out this change between 4.1.4 and 4.1.5 was necessary still IMHO.

**Comment by Incognitas** [comment]
Working as intended in 4.1.6 on windows 10 x64
