### ISSUE TITLE
Num Lock State Ignored

### ISSUE THREAD

**Issue by CipherpunkChris** [4coder-editor/4coder#236]
As of version 4.1.5 - Typing numpad numeric keys treats num lock as off, regardless of toggle. It is not currently possible to input numbers with the numpad.

**Comment by 4th-dimention** [comment]
Please try to use the issue templates moving forward. There isn't nearly enough information in this for me to figure out what's going on. I just tested on Windows and Linux and numpad with numlock inserts numbers in both cases. I don't have any way to test this on Mac, is that your OS?

Can you use the command `display_key_codes` and press the numpad keys with NumLock on and then off to see what key codes are sent?

**Comment by 4coder-editor** [comment]
Please try to use the issue templates moving forward. There isn't nearly enough information in this for me to figure out what's going on. I just tested on Windows and Linux and numpad with numlock inserts numbers in both cases. I don't have any way to test this on Mac, is that your OS?

Can you use the command `display_key_codes` and press the numpad keys with NumLock on and then off to see what key codes are sent?

**Comment by Trisher** [comment]
I have the same problem in 4.1.5. The only key which is correctly recognized of the numblock is 5. The other keys used for navigation which is the behaviour I would expect if the numpad is off.
I'm having a QWERTZ keyboard and Windows 10 x64. Maybe it has the same reason as the undo/redo problem.

**Comment by Trisher** [comment]
0 -> 59
1 -> 61
2 -> 53
3 -> 63
4 -> 54
5 -> NONE
6 -> 55
7 -> 60
8 -> 52
9 -> 62
/ -> 47
* -> 106
- -> 108
+ -> 107
Enter -> 57
Num -> 65

**Comment by 4coder-editor** [comment]
Alright that cleared things up. This problem was caused by the binding by physical location change in Win32 4.1.5. Apparently the translation function I was using ignores numlock and returns the arrow/home/end/etc codes of the numpad. Because the numpad keys do not move around between layouts, I was able to fix this by simply exempting them from physical location translation. Fix in 4.1.6.
