### ISSUE TITLE
Jump list of buffers

### ISSUE THREAD

**Issue by jesusdz** [4coder-editor/4coder#237]
One feature I have been missing a lot is the possibility to jump back through a history of buffers that were previously visible on the active panel. Vim has a feature similar to this but more granular, where using a keyboard shortcut (Ctrl-o in normal mode) we can make the cursor jump back through a history previous cursor positions that can be placed not only in the current buffer, but also in the ones previously shown. I find this a very useful feature that allows fast navigation through a series of symbols that can be distributed over several files, and then going back to the buffer where we are actually coding.

**Comment by 4coder-editor** [comment]
I've added the following:
`jump_to_definition_at_cursor` bound to `[ W Control ]`
`jump_to_last_point` bound to `[ P Control ]`

These work essentially the way you've described the vim feature.

Features in 4.1.6.
