### ISSUE TITLE
Custom command sets

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#24]
4coder already has a lister for executing an arbitrary command, but I ended up implementing my own because I didn't want to have all those extraneous commands in there that I never use.  So I have a specific extended command lister now just for my custom functions (of which there are around 15).

To avoid everyone having to do this themselves, it might be nice to have a simple way to launch an extended command lister using an array of command IDs and have it show only those commands, thus eliminating the need to the user to make this themselves.

Alternatively (or perhaps additionally), there could be a notion of "command category", which could organize commands as part of the DOC system.  Users could make up their own categories, and then instead of passing an array, they'd just pass which doc category (or categories) should be listed.

\- Casey

**Comment by 4coder-editor** [comment]
I implemented the user controlled array of command ids version of this for now.  Command sets are not done but I sort of have a different idea in the works that should basically lead to the same feature.

**Comment by cmuratori** [comment]
What's the function for this?  I should probably switch from mine to yours for consistency...

\- Casey
