### ISSUE TITLE
Emulate Emacs xref find-definitions / pop-marker-stack 

### ISSUE THREAD

**Issue by tomasorti** [4coder-editor/4coder#240]
This is a nice feature very handy when browsing source code.
Emacs xref offers two commands: `xref-find-definitions` and ` xref-pop-marker-stack`.

Lets say we open file `4coder_app_links_allocator.cpp` and go to line 7.

`7 Scratch_Block::Scratch_Block(Application_Links *app){ `

The cursor is on `Application_Links`.
Calling to xref-find-definitions goes to file `4coder_types.h` line 10.

```
10 struct Application_Links{
11    Thread_Context *tctx;
12    void *cmd_context;
13 };
```

Awesome 4coder provides `jump_to_definiton` command, so this could be something like `jump_to_definition_under_cursor`, without prompting for the definition.

Moving cursor to `Thread_Context` and calling to xref-find-definitions goes to file `4coder_base_types.h` line 1353.

```
1353 struct Thread_Context{
1354   Thread_Kind kind;
1355   Base_Allocator *allocator;
1356   Arena node_arena;
...
```

Now, calling xref-pop-marker-stack, goes back to file `4coder_types.h` line 10.
And calling it again, goes back to file `4coder_app_links_allocator.cpp` line 7.

**Comment by 4coder-editor** [comment]
I've added the following:
`jump_to_definition_at_cursor` bound to `[ W Control ]`
`jump_to_last_point` bound to `[ P Control ]`

Which work essentially like what you've described. The custom layer can also add additional points to the stack by calling `point_stack_push` and `point_stack_push_view_cursor` any time.

Features in 4.1.6.
