### ISSUE TITLE
open_all_code crashes

### ISSUE THREAD

**Issue by swifton** [4coder-editor/4coder#245]
Version: 4.1.5

**Repro Steps (Including a snippet of any potentially related customization code)**
Open a file in a folder with code.
Press Alt+X.
Run open_all_code

**Description of the Result**
4coder crashes with a "Segmentation fault" message.

**System**
OS: CentOS 7

**Comment by aolo2** [comment]
Probably addressed by #238 (?)

**Comment by swifton** [comment]
This issue got fixed in 4.1.6.
