### ISSUE TITLE
Numpad keys not working as expected

### ISSUE THREAD

**Issue by PixelBiceps** [4coder-editor/4coder#246]
Version 4.1.5

**Repro Steps (Including a snippet of any potentially related customization code)**
No customization layer

**Description of the Result**
Number pad keys do not input numbers (other than 5) with numlock enabled. Number 1 for example, gives the same behaviour as the end key. UK QWERTY layout is what I use if that information is of any use.

**System**
Windows 10 x64

**Comment by Incognitas** [comment]
Same problem as in #235 
Hopefully this will be fixed soon.

**Comment by j-sarge** [comment]
Yes, similar behaviour here and means things like:

`Bind(toggle_panel_fullscreen, KeyCode_NumPad0, KeyCode_Control);`

do not trigger.

**Comment by Incognitas** [comment]
Please check but it should be fixed in newly released 4.1.6
