### ISSUE TITLE
config.4coder: default_font_name not loading arial.ttf

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#248]
Version: 4.1.5

**Repro Steps (Including a snippet of any potentially related customization code)**
Set the default_font_name to `C:\windows\fonts\arial.ttf` and start 4coder.

**Description of the Result**
The default font will be use (or at least a font that is not arial, monospaced with serif).

**Additional notes**
At least some other proportional fonts seem to work, for example `C:\windows\fonts\LiberationSans-Regular.ttf`.
The result is the same if I copy the files in 4coder's fonts directory.

Another issue is that if I specify the name of a font, for example `Arial Normal` , 4coder starts with a small font (that isn't the one requested). It's not clear if you can specify a font name in default_font_name or if it requires a font FILE name.

A last notes (not really related) is that loading proportional fonts seems a lot slower than monospaced fonts. It's a fraction of a second but noticeable. I'm mentioning it because when launching 4coder from remedybg, it become a lot worst, sometimes up to 10 seconds (but it seems random) where the 4coder window title reads `GRAPHICS`. I will report this to remedybg's dev.

**System**
OS: Windows 7 64bit

**Comment by aolo2** [comment]
Might be related to #205 (?)

**Comment by mrmixer** [comment]
After trying to set a font in 4.1.6, I couldn't set any font yesterday.
I tried again today to try to figure out what was happening and everything seems to work. So it was more likely me doing something wrong or an issue with my system.
