### ISSUE TITLE
Linear or cubic color forms

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#26]
So, this is a pretty hard one to explain, so I apologize if it's weird.

4coder sometimes needs to store colors that you give it.  The typical case might be if you make a lister item, and you want to say what color it is.

However, if you then have live color editing, this breaks because the lister item won't actually update live, since it has the color expanded out as an actual u32 color, not as the theme ID that was used to get the color.

Thankfully, 4coder has a way around this problem, because it allows you to specify an ID as a color instead, and it will expand the color only at render time, thus preserving the ability to edit the color live.  But this, too, breaks once you try to have things like animating colors (say, paste highlight).

To solve _this_ problem, I might recommend the lunatic step of switching to a linear or cubic color form.  This would be a color of the form

struct Color_Form
{
    u8 weight[4];
    u8 color_id[4];
};

This way, colors can still be passed by-register as 64-bit values, so they are not unwieldy, but they internally remain id sets _even across cubic blending_, so any animation you may want to do, or blending as part of a HUD or GUI, can still be live-edited.  At render time, 4coder just fetches the 4 colors by their color_id and adds them together multiplied by their weight value, presumably changing everything to float first.

\- Casey

**Comment by 4coder-editor** [comment]
In lieu of this, we introduced (well Casey did really) the 'Fancy_Color' which can be an rgba value, or two indicies with blend values.  This is not yet used as the color specifier everywhere in the API, but that's probably where it's heading next.
