### ISSUE TITLE
Include string with absolute path don't have the string color

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#260]
Version: 4.1.6

**Repro Steps (Including a snippet of any potentially related customization code)**
```c
#include "Y:\lib\common.h"
```
The string `"Y:\lib\common.h"` loose the string color as soon as the colon is inserted.

**System**
OS: Windows 7 64bit

**Comment by 4coder-editor** [comment]
I had some missing characters in the set for allowed characters in these tokens; fix in 4.1.8
