### ISSUE TITLE
HookID_Layout doesn't work

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#272]
Version: 4.1.6

**Repro Steps**
Starting with an out of the box custom layer, edit `4code_default_hooks.cpp`, near the end of the file, comment
`set_custom_hook(app, HookID_Layout, layout_unwrapped)`
and uncomment
`//set_custom_hook(app, HookID_Layout, layout_unwrapped_small_blank_lines);`

Build the platform layer.

**Description of the Result**
Load a file, the result never uses small blank lines.

**Additional notes**
The hook seems to only be call at application startup, and then 4coder seems to always uses an internal function to perform the layout. This can be checked by setting a breakpoint in the layout function, and see that it's never reached.

**System**
OS: Windows 7 64bit

**Comment by tebtro** [comment]
The actual layout gets set in the begin_buffer hook, so that you could change it depending on the file type you open.

**Comment by mrmixer** [comment]
Thank, I just didn't thought about that.
