### ISSUE TITLE
Has the project been abandoned? 

### ISSUE THREAD

**Issue by ZelCloud** [4coder-editor/4coder#278]
Going through the issues here or the 4coder webstie and docs. There doesn't seem to be a lot of activity or updates. The function docs on the 4coder site don't seem to have been updated since January of this year. Has the project been abandoned, or is there a roadmap or timeline somewhere that I'm just not aware of?

**Comment by netcrns** [comment]
It has not been abandoned. You can subscribe to the [newsletter](http://newsletter.4coder.net/) for some upcoming news.
You could also join the [4coder discord server](https://discord.gg/NQEdQSU) to see what else is being worked on (#editors-of-the-future & #showcase).

**Comment by ZelCloud** [comment]
Good to know, thanks.
