### ISSUE TITLE
custom layer build fails with spaces in 4ed install path

### ISSUE THREAD

**Issue by spectre1989** [4coder-editor/4coder#283]
Version: 4.1.6

**Repro Steps (Including a snippet of any potentially related customization code)**
Using a custom layer with its own build,bat - e.g. Ryan's layer
cd path/to/4coder/custom
4coder_fleury\build

**Description of the Result**
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'cl' is not recognized as an internal or external command,
operable program or batch file.
'cl' is not recognized as an internal or external command,
operable program or batch file.
'metadata_generator' is not recognized as an internal or external command,
operable program or batch file.
'cl' is not recognized as an internal or external command,
operable program or batch file.

**Additional notes**
I'm working through the errors, the first can be fixed by putting quotes around %SCRIPTS_PATH%\setup_cl_generic.bat in setup_cl_xxx.bat

**System**
OS: *Windows 10*

**Comment by spectre1989** [comment]
It looks like I've fixed the remaining issue which is in buildsuper_xxx-win.bat:

set opts=%opts% -I"%custom_root%"

**Comment by 4coder-editor** [comment]
Batch scripts certainly make it complicated. Throwing in quotes can also create issues in places. I did a pass over the build scripts in a case that I setup and it appears to be working better now, but it's hard to be sure. Thanks for the suggested fixes! The new scripts are in vresion 4.1.8.
