### ISSUE TITLE
Add support for drawing buffers with different face ids

### ISSUE THREAD

**Issue by grouse** [4coder-editor/4coder#301]
The default_render_buffer function takes a Face_ID parameter, but it doesn't pass that to draw_text_layout_default and its subsequent children. As far as I can tell, the buffer text is drawn in some way using the text layouts, but there's also no way to supply a Face_ID to newly created text layouts.

My primary use case for this is to draw a few different output buffers (think compilation buffer) with smaller/different font faces than the normal code buffers.

**Comment by mrmixer** [comment]
Buffer have a font face associated to them. You can get and set it with `Face_ID face_id = get_face_id(app, buffer);` and `buffer_set_face(app, buffer, face_id);`.

> My primary use case for this is to draw a few different output buffers (think compilation buffer) with smaller/different font faces than the normal code buffers.

There is something like that by default. Look in `4coder_build_commands.cpp`, search for `set_fancy_compilation_buffer_font`.

**Comment by grouse** [comment]
So there is! Somehow I completely missed that API when searching around, I must've gotten thrown off by the face_id parameter to default_render_buffer
