### ISSUE TITLE
push_buffer_line includes the CR character in CRLF EOL files

### ISSUE THREAD

**Issue by grouse** [4coder-editor/4coder#302]
Version: 4.1.7

When using the push_buffer_line on CRLF line ending mode buffers, the returned string contains the CR character of the CRLF sequence (to be clear, it does _not_ contain the LF character, _only_ the CR character)

In LF line ending mode buffers, it does not contain _any_ line ending character.

push_buffer_line should be changed to behave like it does for LF files.

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Open file with CRLF line endings
2. Call push_buffer_line with a buffer with CRLF line endings

**Description of the Result**

**Additional notes**

**System**
OS: Windows

**Comment by 4coder-editor** [comment]
I just automatically chopped CRs off the end of the string; a lower level deep fix to this would involve changing how various position getters work and looks like it would quickly start breaking other systems. This fix is a bit sloppy but seems okay. Fix in 4.1.8
