### ISSUE TITLE
Jumping to search results of lines of a specific layout just don't work/happen. 

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#32]
Tested using Ctrl + Shift + 'T' search on "..." and "SOMETHING" in these examples, it doesn't seem to matter what the search query is.

These examples can't be jumped to:
```
#if defined(SOMETHING) // EXAMPLE(): _ 
 defined(SOMETHING) // EXAMPLE(): _
(SOMETHING) // EXAMPLE(): _
SOMETHING // EXAMPLE(): _
... // EXAMPLE(): _
... // (): _
```

while these examples seem fine to jump to.
```
#if defined(SOMETHING) // EXAMPLE():  
#if defined(SOMETHING) // EXAMPLE() _
#if defined(SOMETHING) // EXAMPLE()  
... // EXAMPLE() _
... // : _
```

Might it be just having "():" anywhere in the comment? (whitespace between doesn't seem to matter either.)

**Comment by 4coder-editor** [comment]
Fixed in 4.1.0 and later.
