### ISSUE TITLE
Resizing of views slows down depending on how many files have been loaded. (includes GIF)

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#33]
View resizing slows down the more files-are-open/buffers-are-loaded (only 2 views on screen during testing.) 
[Just a mp4.](http://penciltattoo.com/4coder_view_resizing_slows_down_the_more_files_are_open_v0_30.mp4) (in the brown themed part 30-40 files open, in the blue themed one only 2 files are open/loaded.)

**Comment by 4coder-editor** [comment]
Fixed!  4coder used to update all buffer wrap widths during resizing.  Now it only updates the wrap widths of the buffers being viewed.
