### ISSUE TITLE
Disabling virtual whitespace crashes.

### ISSUE THREAD

**Issue by rationalcoder** [4coder-editor/4coder#35]
Migrated from https://4coder.handmade.network/forums/t/3605-crash_when_creating_new_code_file_with_virtual_whitespace_disabled

I would like to create a Vim-like environment with 4coder, but I can't do it without disabling virtual whitespace. However, doing so crashes 4coder when opening a new file and typing a few characters. This may or may not be related to #31.

**Comment by 4coder-editor** [comment]
I have fixed a couple of crash bugs related to opening files/creating new files.  As of right now I cannot reproduce this issue, so when the next build comes out let me know if it's still a problem and I can do more to isolate it.
