### ISSUE TITLE
Keybindings should fall back to unmodified versions when no modified version exists?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#37]
At the moment, I don't exactly understand how keybindings are working, but they seem like perhaps they are slightly off.  If you bind a key to, say, TAB, it will not also bind it to SHIFT-TAB, CTRL-TAB, and ALT-TAB.  This means that people who bind keys have to know ahead of time what all the modifier keys might be for 4coder, and proactively bind them all, perhaps even including all pairwise combinations of modifier keys?

The more sensible thing here, I suspect, is to _prefer_ modifier versions if they _are_ bound, but don't _require_ them to be bound, such that people do not have to proactively bind to lots of modified versions of keys just to ensure that the key will work in all cases that might occur during typing.

If someone _doesn't_ want a specific key combination for some reason, they can always bind that to a "null" function that does nothing, but that doesn't seem like a particularly common case (I've never heard of a situation where someone wants to do something like, "I want TAB to auto-complete all the time EXCEPT when someone is holding down ALT, and then I want it to do nothing").  Usually people want a key to do something, and then they only care about modifier keys to the extent that they want to _change_ the function to something else when that modifier is pressed.

As for why this seems important, for my typing, often times I will not let up on the shift key soon enough before I go to hit backspace or an arrow key or something like this.  If I _don't_ bind all my special keys to MDFR_NONE _and_ MDFR_SHIFT, I just get nothing happening in those cases.  This seems unnecessary, and like I said before, creates a weird situation where the user has to foresee all possible ways that a keyboard may have modifiers in the future in order to ensure that their keys will always work.

\- Casey

**Comment by 4coder-editor** [comment]
Deprecated issue in favor of: #52
