### ISSUE TITLE
Color highlighting doesn't seem to merge like syntax highlighting does?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#39]
This may be "user error", but as far as I can tell, syntax highlighting properly merges with region highlighting, such that if you specify 0 for a region highlight value (say, the font foreground color), then the syntax highlighting color of the underlying text remains unchanged.  This allows you to do things like set the background color of a region without affecting the underlying text colors.

However, overlapping highlight regions _do not_ seem to obey this principle, such that if you create two regions that overlap, only one can take affect for any given character, they cannot "merge" even if one of the overlapping ones has 0 in one of the slots.

It would be preferable to allow regions to merge, such that you can have as many overlapping regions as you want, and any 0 values are treated as allowing pass-through from another overlapping region that does specify that value.

\- Casey

**Comment by 4coder-editor** [comment]
Deprecated issue in favor of: #52

**Comment by 4coder-editor** [comment]
I believe I now have this cleaned up and working.
