### ISSUE TITLE
File_Attributes type for getting backing file information like size and write time

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#4]
I went ahead and added this to the core, and it's very useful for the custom layer:

```
STRUCT File_Attributes{
    uint64_t size;
    uint64_t last_write_time;
};
```

This tells you how big the backing file is, and the last time someone wrote to it.  I made an API for getting this at any time from a buffer:

```
API_EXPORT File_Attributes
Get_Buffer_File_Attributes(Application_Links *app, Buffer_ID buffer)
{
    File_Attributes result = {};
    
    Models *models = (Models*)app->cmd_context;
    if (buffer != 0){
        Editing_File *file = imp_get_file(models, buffer);
        result.last_write_time = file->attribs.last_write_time;
        result.size = file->attribs.size;
    }
    
    return(result);
}
```

I track it throughout the file process, so previously when you were just getting the size in the core, I just keep the entire attribute struct:

```
internal
Sys_Load_Attributes_Sig(system_load_attributes){
    HANDLE file = *(HANDLE*)(&handle);
    BY_HANDLE_FILE_INFORMATION info;
    GetFileInformationByHandle(file, &info);
    
    Plat_File_Attributes result = {};
    result.size = ((u64)info.nFileSizeHigh << 32LL) | ((u64)info.nFileSizeLow);
    result.last_write_time = ((u64)info.ftLastWriteTime.dwHighDateTime << 32LL) | ((u64)info.ftLastWriteTime.dwLowDateTime);
    
    return(result);
}
```

You can also do this without the handle, so you can return this information for files you haven't opened, which would be a nice way to show information in the lister panel.  You'd just use GetFileAttributesExW, and it will return the same information using the name of the file.

Similarly, I would highly recommend switching away from the notification stuff, which seems super buggy, and just calling GetFileAttributesExW on a background thread or when you thing it's appropriate.  It will not lock anything or acquire any handles, so it should not have the same interference problems!  Similarly, you can "abstract" this call into an OS-agnostic thing by making a platform-independent call that vectors to GetFileAttributesExW on Windows and to stat() on Linux, and then your change tracking can be platform-independent, too.

\- Casey

**Comment by 4coder-editor** [comment]
The File_Attributes is now setup in the system for windows.  The notification system still has to be redone to use the attributes for notifications.
