### ISSUE TITLE
THE DREADED PURPLE FLASH

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#43]
So, I think it isn't so hard to figure out where the dreaded purple flash is coming from, and I have made some progress after only a few minutes of tinkering.

The 4coder background is cleared to **DREADED PURPLE** before rendering begins, so it's not surprising when you see **DREADED PURPLE** - it just means that some part of the screen didn't get drawn.

I can _force_ a **DREADED PURPLE FLASH** to occur very easily now.  If I just sink enough draw calls to overflow the render partition, the flash will occur.  This is because pushing a render call onto the render stack requires space in the partition, and the check for "out" during the copy will fail and skip inserting the draw calls into the list.  This means that if you just overflow the draw sink during updating of, say, one of the two views on the screen, if the second view hasn't been processed yet, the entire thing will flash purple because none of its draw calls (including the background clear) will occur.

The larger issue is _why_ the render partition is running out of space.  Since I don't know that much about 4coder's memory partitioning schemes, I couldn't really say for sure without more investigation.  But my suspicion would be that it is because 4coder doesn't use separate partitions, it uses one partition that gets split.  As I've said in other bug reports, I don't think that is a good idea for an editor.  4coder should have one (growable!) partition for each logical thing that is allocated together, so the renderer stack should be its own arena that can grow and that is unrelated to any other arena.  I suspect that once that is done, the purple flash will go away on its own...

\- Casey

**Comment by 4coder-editor** [comment]
Added the new DREADED GREEN FLASH to distinguish types of bugs.  We'll see what happens.
