### ISSUE TITLE
Feature Request: Filebar customisation

### ISSUE THREAD

**Issue by Bulmanator** [4coder-editor/4coder#46]
I think it would be nice if we could change the contents of the filebar to display the information in a format that we choose, maybe through a format string a bit like Vim does its statusline or exposing the displayable fields in a struct that we pass at initialisation/ on specific file type opening.
Setting the position would also be nice, like placing it at the bottom or along the outsides of a buffer.

**Comment by 4coder-editor** [comment]
After working on the immediate mode render caller API, and then user margins, it became possible to fully render the file bar in the custom layer, so the file bar is now 100% customizable.  I will later introduce a helper layer for simple customizations where you don't want to have to take over the rendering.

**Comment by Bulmanator** [comment]
This sounds super cool! I look forward to it being released. As you talk about user margins, is it also possible to draw line numbers down the side now?

**Comment by 4coder-editor** [comment]
Yes this is possible now, and I will be including a built in option for enabling line numbers in this version.
