### ISSUE TITLE
Token Highlighting On Empty Code File Causes Read Access Violation in seek_token_right

### ISSUE THREAD

**Issue by peter-slattery** [4coder-editor/4coder#47]
In my custom layer, I've made a copy of `default_render_caller` and modified it so that `do_token_highlight = true`. This works fine until you try and create a new code file at which point you get a read access violation.

The lines in question are:
```
int32_t pos0 = view.cursor.pos;
int32_t pos1 = buffer_boundary_seek(app, &buffer, pos0, DirLeft, token_flags);
int32_t pos2 = buffer_boundary_seek(app, &buffer, pos1, DirRight, token_flags);
```

The read access violation occurs in the second `buffer_boundary_seek`, down inside `seek_token_right`. The issue is that `seek_token_right` calls `cpp_get_token` on a tokens array with a count of 0, which returns -1. `seek_token_right` doesn't then check to see if the returned index is less than zero, and looks into `tokens->tokens + (-1)`, causing the read access violation.

I also noticed that even though the crash occurs on the second call to `buffer_boundary_seek`, the value of the first one is also incorrect (I'm seeing pos1 equal to 1701080931), though it doesn't cause a crash.

For anyone who encounters this issue before it's fixed (which probably has to do with how tokens are retreived, and isn't part of the custom layer we can fix ourselves), two fixes come to mind:
1. Just check to see if buffer size is 0 in the render caller before attempting to highlight tokens. This is what I've gone with and is working so far.
2. Check that the result of `cpp_get_token` is greater than zero before use. I'm not doing this simply because `seek_token_right` works everywhere else so far and I don't know if there's a reason the value of `cpp_get_token` isn't checked.

**Comment by cmuratori** [comment]
I'm 99% sure I already reported this, and it already got fixed, but I think Allen has not pushed a new version since then... Allen, this is the same bug, yes?

\- Casey

**Comment by 4coder-editor** [comment]
Yes this bug is fixed in my current build and the fix will be in the next build!
