### ISSUE TITLE
The key binding system we talked about on the stream

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#52]
Key bindings now do:

1) There is one key which is the "activation" key which says when event checking for this binding will happen,

2) There is a set of (10 at maximum?) modifier keys listed which all must be down to trigger the event,

3) Events are sorted from most to least modifiers off of the activation key.

4) Dispatch on the event occurs when the activation key happens and the scan of the chain off the activation key hits the first complete modifier match.

\- Casey

**Comment by 4coder-editor** [comment]
This is how things work in 4.1.0 and later except for a matching bug fixed in 4.1.5.
