### ISSUE TITLE
MacOS: Option Key Support

### ISSUE THREAD

**Issue by StrangeZak** [4coder-editor/4coder#57]
Seems like theres support for the command button, but not the option key. Can we get support added for this as it seems like its kinda a good thing to have (Unless the option key is some sort of crazy key in MacOS). 

Thanks
-Zak

**Comment by 4coder-editor** [comment]
I believe the option key is bound to mdfr_alt (and in the next mac build key_alt).

**Comment by StrangeZak** [comment]
mdfr_alt isnt working on my setup. Im just using the `fill_keys_default` function (the non-mac version).

**Comment by 4coder-editor** [comment]
Interesting, that just sounds like a bug, then.  I just double checked the keyboard handling and it's supposed to be mapping option modifies to the ALT modifier flag and index.

**Comment by StrangeZak** [comment]
Awesome, check it out and let me know what you find!

**Comment by 4coder-editor** [comment]
The option key is now bound to KeyCode_Alt in 4.1.0 and later. Unless there's a new confirmation of it not working I'll consider this closed.
