### ISSUE TITLE
virtual whitespace not enabled when project is loaded automatically

### ISSUE THREAD

**Issue by Dautor** [4coder-editor/4coder#60]
I've set automatically_load_project to true and the files it opens automatically have no virtual whitespace enabled.
Reloading files enables virtual whitespace on them.
(I'm on Linux.)

**Comment by 4coder-editor** [comment]
I found a similar problem with files on the command line, where the command line files were opened before the configuration was loaded.  I am not sure why you are getting this with files loaded in the project automatically, in the default start hook the project is loaded after the config is loaded and it works.

Double check your start hook if you've customized it.

**Comment by Dautor** [comment]
OK, so I looked at it closer and I'm able to reproduce it with a vanilla build.
It is not automatic project loading that causes it but loading files from command line.
~/4coder/4ed a.cpp b.cpp will result in files not having virtual whitespace enabled.
