### ISSUE TITLE
setup_cl_generic.bat support for VS 2017 Professional

### ISSUE THREAD

**Issue by StrangeZak** [4coder-editor/4coder#64]
I have to use Visual Studio 2017 professional because of work, and noticed that this was missing from your setup_cl_generic.bat file. Feel free to take it or leave:

Add the following to the end of the batch file

`
SET VC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
IF NOT DEFINED LIB (IF EXIST "%VC_PATH%" (call "%VC_PATH%\VC\Auxiliary\Build\vcvarsall.bat" %1))
`

**Comment by 4coder-editor** [comment]
Ahh thanks for the note.  Added it to the script.
