### ISSUE TITLE
4coder freezes in the file open panel

### ISSUE THREAD

**Issue by edrickhong** [4coder-editor/4coder#65]
This is strictly when using Wayland. I am using Fedora 29 with 4coder version 4.0.3
This issue is not observed under a standard Xorg session

**Comment by edrickhong** [comment]
This is the stack trace during the freeze. Seems to happen when typing 

`#0  0x00007ffff7647ca9 in __GI___poll (fds=0x7fffffffa468, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff753f917 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff754162a in xcb_wait_for_special_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fffa5d11f7b in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#4  0x00007fffa5d120c8 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#5  0x00007fffa5d1330e in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#6  0x00007fffa5d1416c in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#7  0x00007fffa4b04c36 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007fffa4b00314 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#9  0x00007fffa494229a in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#10 0x00007fffa4942a8f in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#11 0x00007fffa48ff6f8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#12 0x00007fffa49074ef in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#13 0x00000000004063db in interpret_render_buffer (t=0x76fea0 <target>, growable_scratch=0x770420 <shared_vars+32>) at /home/allen/4ed/code/opengl/4ed_opengl_render.cpp:100
#14 main (argc=<optimized out>, argv=<optimized out>) at /home/allen/4ed/code/platform_linux/linux_4ed.cpp:2248`

I have moved to Ubuntu 18.10 . 
Issue is still strictly under a Wayland session. I did not have this problem using older 4coder builds that does not have the lister panel api implemented, so the problem likely lies there. Standard Mesa GL drivers.

**Comment by 4coder-editor** [comment]
Because this happened in OpenGL code, I'm guessing it's a graphics bugs. Most graphics bugs are fixed in 4.1.0 and later - although there are new ones related to Linux OpenGL support. Either way, not sure this issue is still a thing.
