### ISSUE TITLE
Font rendering goes bad when mouse enters window

### ISSUE THREAD

**Issue by joestraitiff** [4coder-editor/4coder#66]
I recently received a new gaming laptop and 4coder does not play well with this machine (it works fine on my desktop and on a macbook I tried it on).  I'm not certain why it happens on this machine but after opening vanilla alpha 4.0.30 super! the fonts appear normally but as soon as I move the mouse into the window each character renders as a box and sometimes the display flashes rapidly as I move the mouse.

Here's a screengrab to show it happening https://media.giphy.com/media/8hZr5UW9ZWqMYvpz3U/giphy.mp4
![Font Rendering Bug](https://media.giphy.com/media/8hZr5UW9ZWqMYvpz3U/giphy.gif)

I can provide any details of the hardware to help you out...  It's 64-bit windows 10 home, i7-8750h processor.  It's a gaming laptop and has 2 graphics processors in it a gtx 1060 and an Intel UHD Graphics 630.  However, the bug appears when running 4ed.exe with either graphics processor.  It also has a 120hz display.  However, the bug appears even on a 60hz display hooked up externally...

I'm at a loss at what to try next.

**Comment by 4coder-editor** [comment]
I am not sure because I never had a repro for this to begin with, but most graphics issues are fixed in 4.1.0 and later.
