### ISSUE TITLE
Left pane goes entirely pink when navigating a BMP file

### ISSUE THREAD

**Issue by BluBloos** [4coder-editor/4coder#67]
Hi, I'm using version 4.0.29
If I open a BMP file and scroll down far enough, the left pane turns entirely pink. Note that the issue only happens if the BMP file is opened in the right pane. I am able to reliably replicate the issue by following the steps described above. 
Here is a video to see the issue in action.
[https://youtu.be/HNIbjETTbn8](url)

**Comment by 4coder-editor** [comment]
The pink screen and screen flicker bugs are all fixed in 4.1.0 and later.
