### ISSUE TITLE
Are we sure this is the right way to set hooks?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#68]
Right now there is a lot of business involved in setting hooks through the core.  There's like the enum for the hook, a package that captures that into a packet for storage, and switch statement that breaks that back out, then it sets it on the models.  And it's "zero if unset", which means everywhere that ever calls a hook has to check for zero.

Is there a good reason not to just do:

1) At startup, all hooks are set to stub functions, so you can always just call one and it won't crash.  If the user does a "set to zero", it just puts the stub function in instead.

2) The calls to set hooks just set the hooks directly in the models struct.

This would get rid of the enums, the switch/case, the packets, and the if()'s around every call.  It would only add one small thing, which is that set_blah_hook functions have to do "models->hook = (hook == 0) ? stub : hook;" instead of just cold-setting the hook, assuming you want to gracefully handle the user passing 0.

I am assuming there actually _are_ reasons why it's not this way, but I figured I'd check because it might also be that there used to be reasons but now there aren't anymore, etc...

- Casey

**Comment by 4coder-editor** [comment]
As of 4.1.0 this is (essentially) how things work.
