### ISSUE TITLE
Add a "clipboard changed" hook

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#69]
I added one myself, but it's probably janky.  Basically there should be a hook that's like:

`void clipboard_change(Application_Links *app, String contents, u32 flags);`

The flags would have at least "clipboard_from_os", which would be set if the incoming clipboard change was one that came from the outside, as opposed from inside 4coder.

\- Casey

**Comment by 4coder-editor** [comment]
I adopted this pretty much without changing it.  I just changed the flag name to my usual naming style "ClipboardFlag_FromOS".
