### ISSUE TITLE
Function clipboard_index has incorect behavior or documentation

### ISSUE THREAD

**Issue by KalinMagus** [4coder-editor/4coder#71]
The documentation at http://4coder.net/custom_docs.html#clipboard_index_doc says that clipboard_index will fill the output buffer with a partial copy of the clipboard if it's called with a buffer that's too small. This doesn't actually happen if the clipboard contents exceed the buffer size. Instead the buffer is unchanged and the full length is returned as if a null buffer was passed instead. I would prefer that I could get a partial clipboard contents as I want to display a preview of it's contents (instead of allocating every time), but if not the documentation should be fixed.

```
char preview[64];
int32_t preview_len = clipboard_index(app, 0, 0, preview, ArrayCount(preview));
// if the clipboard size exceeds 64 bytes no data is copied
```

**Comment by 4coder-editor** [comment]
All of the string API's were inconsistent and busted.  The new build will feature standardized string-returning that should be a lot easier to use, and the documentation will be updated to suit.
