### ISSUE TITLE
Windows 7 full screen glitch

### ISSUE THREAD

**Issue by flowless1** [4coder-editor/4coder#72]
The full screen window would be "frozen", unfocused (without cursor), and unusable.
It works normal when maximized.
Tried with
```
4ed -F
4ed -F -S
4ed -f 16 -F
```
![image](https://user-images.githubusercontent.com/48275400/54633089-bcc77100-4a7f-11e9-98a0-8b6e1af602ca.png)
![image](https://user-images.githubusercontent.com/48275400/54633143-db2d6c80-4a7f-11e9-9f0c-cf35088e668d.png)
![image](https://user-images.githubusercontent.com/48275400/54633147-df598a00-4a7f-11e9-963e-f51ddf4218f0.png)

**Comment by 4coder-editor** [comment]
This appears to be fixed in 4.1.0 and later - please reopen if it is not fixed.
