### ISSUE TITLE
No red '!' indicator for files delete outside of 4Coder.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#73]
If a file is open inside 4Coder is delete outside of 4Coder the buffer doesn't get that red '!' indicator(or anything) need to make a minimal change to get the '*' then you can save and the file reappears , I don't remember seeing this before v0.30.

Repro: 
Start 4Coder, 
create a new file, 
save the new file, 
delete the file in Windows explorer, 
voila buffer with data without a file on disk with no indication of the file not existing.

**Comment by 4coder-editor** [comment]
Fixed in 4.1.3.
