### ISSUE TITLE
Unable to input diacritics using dead keys

### ISSUE THREAD

**Issue by thorduragust** [4coder-editor/4coder#81]
4coder is able to display diacritics, but not input some of them, specifically ones that
require a dead key to input.
Example of diacritics I am thinking of are áéíúý. On my layout these use the dead key.
If it helps, I am on macos and I am using an icelandic keyboard layout.

**Comment by mrmixer** [comment]
You might need to provide more information here such as your keyboard layout, OS and what diacritics you are trying to input and which key they use.
I can input at least some diacritic on my keyboard layout in 4coder. For example: âäáàǎāã work as expected.

**Comment by thorduragust** [comment]
> You might need to provide more information here such as your keyboard layout, OS and what diacritics you are trying to input and which key they use.
> I can input at least some diacritic on my keyboard layout in 4coder. For example: âäáàǎāã work as expected.

You are right, I have updated the post :)

**Comment by 4coder-editor** [comment]
This bug was an issue with the Mac layer not implementing the NSTextInputClient protocol. It should be fixed in 4.1.5
