### ISSUE TITLE
macOS blurry font rendering

### ISSUE THREAD

**Issue by ianrtaylor** [4coder-editor/4coder#83]
This is a copy of https://4coder.handmade.network/forums/t/3427-os_x_blurry_font_rendering.

Fonts are currently blurry on macOS, making the screens difficult to read. 
I'm using a Mid 2015 MacBook Pro w/ Retina display, running macOS Mojave -- I believe other mac systems are affected as well.

**Comment by 4coder-editor** [comment]
This is fixed in 4.1.3 and later.
