### ISSUE TITLE
Grouping several commands into a single undo step

### ISSUE THREAD

**Issue by mrmixer** [4coder-editor/4coder#86]
I would like to be able to "group" some commands into one undo item.

For example, I have a function that selects and deletes a scope if there was a '{' on the line, and than use replace_range to remove the line except for an eventual '}' at the start of the line.

If I press undo after the function is called, it only undoes the replace range. I need to undo a second time to undo the delete_current_scope call. I would like a way to only have to undo once.

**Comment by 4coder-editor** [comment]
This is now an option in 4.1.0 and later.
