### ISSUE TITLE
4coder crashes on open a non created file and paste code quickly

### ISSUE THREAD

**Issue by ArsDankeZik** [4coder-editor/4coder#89]
**I have a bug. I open 4ed by cmd/cmder and paste quickly a bunch of code copied previously from a website, crashes.**

**Executed cmd:** _4ed window.cpp (the file not exist)_
**4coder version:** _alpha 4.0.30_
**Windows version:** _Windows 10 Home_

**Comment by LoryMaster** [comment]
I have seen the same crash happen even without pasting. Just simply trying to write to the buffer crashes, and only when starting from a prompt.

**Comment by 4coder-editor** [comment]
This is an old bug and should be fixed in 4.1.0 and later.
