### ISSUE TITLE
Token types are hard to use directly because they are not sufficiently granular

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#9]
At the moment, I often have to get the text of a token to check to see which sub-class of token it is.  For example, if the lexer says it's a "type keyword", I usually need to know which one, since enums and structs will be parsed differently.  Since the lexer already had to know this information, it would be nice if the tokens either:

a) were typed according to their granular type, such as STRUCT and ENUM, and then you could use compound macros or predicate functions to ask about larger supersets like "type keyword", or

b) had a sub-type field with the granular type, so you can keep the scheme you have now, but users needing the more specific type of token could still get it without resorting to buffer-read-plus-string-compare.

\- Casey

**Comment by 4coder-editor** [comment]
I addressed this by creating the "granular type" for each keyword in C/C++ and a secondary "category" enum with a helper that takes Cpp_Token_Type to Cpp_Token_Category so that places using the high level types for parsing can still behave the same way.
