### ISSUE TITLE
Crash when opening directory

### ISSUE THREAD

**Issue by Knufy21** [4coder-editor/4coder#90]
My 4coder 4.0.30 (using Windows 10) crashes when I try to open a directory that has a file named `awndongfawengfasngfnseglnsolegnolsenggashiderujgasöjnrgasirugnasöejrngaerignaeörgnaerugnaerögnaerögnaergnaergöaerngaergnaelrjgnaergbalergbalergbaliergbaelrigbaergijbalergbalergbaergbaleirgbaerlgjbaergbalergaaaa` in it. The length of the file name does not seem to be the problem. You can replace some characters with others and sometimes it will not crash the program but other times it will. Copying the file name and creating a new file with it will only work on the desktop because there you can apparently type some more characters than in the explorer program.

**Comment by 4coder-editor** [comment]
This appears to be fixed in 4.1.0 and later.
