### ISSUE TITLE
Feature Request: Customizable Virtual Whitespace

### ISSUE THREAD

**Issue by kaervin** [4coder-editor/4coder#91]
It would be nice if 4coder could support the customization of virtual whitespace.
Giving users the ability to change how virtual whitespace behaves, would make it possible for users to add better support for more languages, and make indentation fit to their preference.

**Comment by 4coder-editor** [comment]
This is possible as of 4.1.0. There is still some work that needs to be done to make it convenient to integrate multiple languages, and to make the customization mechanism more approachable, but I'm closing this issue as those problem are brought up by new specific issues.
