### ISSUE TITLE
Add default mapping for switching between 2 recent buffers

### ISSUE THREAD

**Issue by paulriddle** [4coder-editor/4coder#96]
4coder is meant to be convenient out of the box without any customizations. I think it would be very useful to add one default mapping for switching between two most recent buffers.

```
-----                -----                -----
|A|B| -- (Alt+\) --> |A|C| -- (Alt+\) --> |A|B|
-----                -----                -----
```

I thought about it while doing the following. I have code in `A` and `C`. I compile with Ctrl+m. I do Ctrl+z to run the executable, it prompts me for the buffer name `B` and name of the executable, `main.exe`. After I took a look at the output of `main.exe` I want to be able to quickly switch back to the code in `C`.

This is my current situation but there might be many more use cases. It might even be a good idea to just rotate between all buffers with `Alt+[` and `Alt+]`.

Right now all you have by default is Ctrl+i which requires typing some text.

**Comment by 4coder-editor** [comment]
Implemented as the command `quick_swap_buffer` default bound to [ Backslash Alt ] on 4.1.5.
